<div style="text-align:center; margin:24px 0;">
  <h2 style="color:#48C9B0; margin-bottom:8px;">Audit des datasets médicaux SFT et DPO</h2>
  <p margin:0;">Analyse préalable à la préparation des données d’entraînement</p>
</div>

<div style="text-align:center; margin:24px 0;">
  <h2 style="color:#48C9B0;">🧩 Sommaire</h2>
</div>

1. Cadre, documentation et configuration  
2. Chargement et table canonique d’audit  
3. Audit structurel  
4. Audit des QCM  
5. Audit textuel  
6. Répétitions, quasi-doublons et contradictions  
7. Audit de diversité  
8. Audit médical, sécurité clinique et triage  
9. Audit RGPD  
10. Audit DPO  
11. Audit des fuites entre splits  
12. Synthèse globale et export des rapports


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
  <strong>Objectif :</strong><br/>
  Auditer les datasets médicaux destinés au SFT et au DPO afin d’identifier les problèmes de qualité, de structure, de cohérence, de confidentialité et de séparation des données avant leur nettoyage.
</div>

<p>
  Ce notebook analyse les données sources sans les modifier. Il centralise les contrôles nécessaires à la définition des règles qui seront ensuite appliquées dans le notebook de nettoyage.
</p>

<p>
  L’audit s’appuie sur une représentation canonique commune aux différents datasets afin de comparer leurs caractéristiques malgré l’hétérogénéité de leurs formats d’origine. Les résultats sont regroupés dans des rapports structurés et exportés pour assurer la traçabilité des décisions de préparation des données.
</p>

<h2 style="color:#48C9B0; margin-top:15px; margin-bottom:8px;">
  1. Cadre, documentation et configuration des corpus
</h2>

<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
  <strong>Objectif :</strong><br>
  Présenter les corpus sélectionnés et analyser leur documentation afin d’identifier leur structure, leur provenance, leur licence, leur usage potentiel et leurs principales limites avant l’analyse des données.
</div>

<p>
  Quatre corpus médicaux ont été retenus : <strong>FrenchMedMCQA</strong>,
  <strong>MedQuAD / MedQuad-KV</strong>, <strong>MediQAl</strong> et
  <strong>UltraMedical-Preference</strong>. Ils sont complémentaires par leur langue,
  leur structure et leur contenu et pourront contribuer à la constitution des datasets
  destinés au <strong>SFT</strong>, au <strong>DPO</strong> ou à l’<strong>évaluation</strong>.
</p>

<p>
  Les informations présentées dans cette section proviennent des README et des
  <em>dataset cards</em>. Elles constituent une référence documentaire qui sera
  ensuite confrontée aux données réellement chargées.
</p>

<h3 style="color:#48C9B0; margin-top:20px; margin-bottom:8px;">
  1.1 Présentation, structure et usage prévu
</h3>

<p>
  Les corpus ont été sélectionnés pour couvrir plusieurs formats d’apprentissage :
  QCM médicaux, questions-réponses ouvertes et paires de préférences.
  Leur usage initial est défini à partir de leur documentation et pourra être
  réévalué selon les résultats de l’audit.
</p>

<table style="width:100%; border-collapse:collapse;">
  <thead>
    <tr style="background-color:#48C9B0; color:white;">
      <th style="padding:8px; border:1px solid #ddd;">Corpus</th>
      <th style="padding:8px; border:1px solid #ddd;">Langue</th>
      <th style="padding:8px; border:1px solid #ddd;">Structure / contenu</th>
      <th style="padding:8px; border:1px solid #ddd;">Taille annoncée</th>
      <th style="padding:8px; border:1px solid #ddd;">Usage prévu</th>
      <th style="padding:8px; border:1px solid #ddd;">Statut</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>FrenchMedMCQA</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Français</td>
      <td style="padding:8px; border:1px solid #ddd;">
        QCM à réponse unique ou multiple :
        <code>id</code>, <code>question</code>, <code>answers</code>,
        <code>correct_answers</code>, <code>subject_name</code>, <code>type</code>
      </td>
      <td style="padding:8px; border:1px solid #ddd;">3 105 questions</td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>SFT</strong></td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>Confirmé</strong></td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MedQuAD / MedQuad-KV</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Anglais</td>
      <td style="padding:8px; border:1px solid #ddd;">
        Questions-réponses médicales :
        <code>qtype</code>, <code>Question</code>, <code>Answer</code>
      </td>
      <td style="padding:8px; border:1px solid #ddd;">47 457 paires QA pour MedQuAD original</td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>SFT</strong></td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>À confirmer</strong></td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MediQAl MCQU / MCQM</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Français</td>
      <td style="padding:8px; border:1px solid #ddd;">
        QCM et cas cliniques :
        <code>id</code>, <code>clinical_case</code>, <code>question</code>,
        réponses A-E, <code>correct_answers</code>,
        <code>medical_subject</code>, <code>question_type</code>
      </td>
      <td style="padding:8px; border:1px solid #ddd;" rowspan="2">32 603 questions pour MediQAl</td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>SFT</strong></td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>Confirmé</strong></td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MediQAl OEQ</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Français</td>
      <td style="padding:8px; border:1px solid #ddd;">
        Questions ouvertes :
        <code>id</code>, <code>clinical_case</code>, <code>question</code>,
        <code>answer</code>, <code>medical_subject</code>, <code>question_type</code>
      </td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>Évaluation</strong></td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>Confirmé</strong></td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>UltraMedical-Preference</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Anglais</td>
      <td style="padding:8px; border:1px solid #ddd;">
        Paires de préférences :
        <code>prompt_id</code>, <code>label_type</code>, <code>prompt</code>,
        <code>chosen</code>, <code>rejected</code>, <code>metadata</code>,
        <code>feedback</code>
      </td>
      <td style="padding:8px; border:1px solid #ddd;">Environ 110 000 exemples</td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>DPO</strong></td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>Confirmé</strong></td>
    </tr>
  </tbody>
</table>

<p>
  <strong>FrenchMedMCQA</strong> et <strong>MediQAl MCQU / MCQM</strong>
  constituent les principales sources francophones envisagées pour le SFT.
  <strong>MedQuAD / MedQuad-KV</strong> apporte des questions-réponses médicales
  anglophones, sous réserve de validation de la variante utilisée.
  <strong>MediQAl OEQ</strong> est réservé à l’évaluation car il est uniquement
  disponible sous forme de split <code>test</code>.
  <strong>UltraMedical-Preference</strong> est destiné au DPO grâce à sa structure
  <code>prompt / chosen / rejected</code>.
</p>

<h3 style="color:#48C9B0; margin-top:20px; margin-bottom:8px;">
  1.2 Provenance et licences
</h3>

<p>
  La provenance et les licences permettent d’évaluer les conditions de réutilisation
  des corpus et d’assurer la traçabilité des exemples qui pourront être conservés
  dans les datasets finaux.
</p>

<table style="width:100%; border-collapse:collapse;">
  <thead>
    <tr style="background-color:#48C9B0; color:white;">
      <th style="padding:8px; border:1px solid #ddd;">Corpus</th>
      <th style="padding:8px; border:1px solid #ddd;">Provenance documentée</th>
      <th style="padding:8px; border:1px solid #ddd;">Licence</th>
      <th style="padding:8px; border:1px solid #ddd;">Statut</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>FrenchMedMCQA</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Questions issues d’examens français de spécialisation en pharmacie.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">Apache-2.0</td>
      <td style="padding:8px; border:1px solid #ddd;">Documentée</td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MedQuAD / MedQuad-KV</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        MedQuAD original a été construit à partir de 12 ressources médicales
        de confiance, principalement issues du NIH. La correspondance exacte
        avec la variante locale MedQuad-KV reste à vérifier.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">CC BY 4.0 pour MedQuAD original</td>
      <td style="padding:8px; border:1px solid #ddd;"><strong>À confirmer pour MedQuad-KV</strong></td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MediQAl</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">Questions provenant d’examens médicaux français.</td>
      <td style="padding:8px; border:1px solid #ddd;">CC BY 4.0</td>
      <td style="padding:8px; border:1px solid #ddd;">Documentée</td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>UltraMedical-Preference</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Extension d’un corpus biomédical regroupant des prompts et plusieurs
        réponses produites ou évaluées pour constituer un dataset de préférences.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">MIT</td>
      <td style="padding:8px; border:1px solid #ddd;">Documentée</td>
    </tr>
  </tbody>
</table>

<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
  <strong>Point à confirmer :</strong><br>
  La provenance et la licence applicables à la variante locale
  <strong>MedQuad-KV</strong> doivent être vérifiées avant son utilisation définitive
  pour l’entraînement.
</div>

<p>
  Chaque exemple retenu devra conserver sa <strong>source</strong>,
  son <strong>identifiant d’origine</strong> et les informations de
  <strong>licence</strong> nécessaires à sa traçabilité.
</p>

<h3 style="color:#48C9B0; margin-top:20px; margin-bottom:8px;">
  1.3 Limites documentaires et contrôles à réaliser
</h3>

<p>
  La documentation permet d’identifier plusieurs points de vigilance.
  Ces éléments ne constituent pas une preuve de qualité et devront être vérifiés
  directement dans les données pendant l’audit.
</p>

<table style="width:100%; border-collapse:collapse;">
  <thead>
    <tr style="background-color:#48C9B0; color:white;">
      <th style="padding:8px; border:1px solid #ddd;">Corpus</th>
      <th style="padding:8px; border:1px solid #ddd;">Point de vigilance</th>
      <th style="padding:8px; border:1px solid #ddd;">Contrôle à réaliser</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>FrenchMedMCQA</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Corpus principalement orienté pharmacie. Le README déclare l’absence
        de données personnelles ou sensibles.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">
        Vérifier la diversité médicale et contrôler directement la présence
        éventuelle de données personnelles.
      </td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MedQuAD / MedQuad-KV</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Correspondance entre la variante locale et le corpus original non confirmée.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">
        Vérifier la provenance, la licence et les éventuelles transformations
        appliquées au corpus.
      </td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>MediQAl</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Plusieurs formats coexistent et certaines questions peuvent dépendre
        d’un contexte clinique. OEQ est uniquement disponible en <code>test</code>.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">
        Auditer séparément MCQU, MCQM et OEQ et vérifier l’autonomie
        des questions par rapport aux cas cliniques.
      </td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #ddd;"><strong>UltraMedical-Preference</strong></td>
      <td style="padding:8px; border:1px solid #ddd;">
        Préférences principalement évaluées par GPT-4, avec un risque de biais
        d’annotation. Les catégories <code>easy</code>, <code>hard</code>,
        <code>length</code> et <code>human</code> nécessitent une analyse.
      </td>
      <td style="padding:8px; border:1px solid #ddd;">
        Auditer les métadonnées, les labels, les répétitions, les couples
        <code>chosen / rejected</code> et les éventuels biais de préférence.
      </td>
    </tr>
  </tbody>
</table>

<h3 style="color:#48C9B0; margin-top:20px; margin-bottom:8px;">
  1.4 Synthèse et décision préliminaire
</h3>

<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
  Les quatre corpus sont conservés dans le périmètre de l’audit.
  <strong>FrenchMedMCQA</strong> et <strong>MediQAl MCQU / MCQM</strong>
  sont principalement destinés au <strong>SFT</strong>,
  <strong>MediQAl OEQ</strong> à l’<strong>évaluation</strong> et
  <strong>UltraMedical-Preference</strong> au <strong>DPO</strong>.
  L’utilisation de <strong>MedQuAD / MedQuad-KV</strong> pour le SFT reste
  conditionnée à la confirmation de sa provenance et de sa licence.
  <br><br>
  La sélection définitive des exemples dépendra des audits structurels,
  qualitatifs, médicaux, de confidentialité et de séparation des données.
  Les données retenues devront conserver les informations nécessaires
  à leur provenance et à leur traçabilité.
</div>

In [1]:
from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
import ast
import hashlib
import json
import random
import re
import unicodedata

import numpy as np
import pandas as pd
from IPython.display import display


# Chargement des dépendances optionnelles

try:
    from langdetect import DetectorFactory, detect
    from langdetect.lang_detect_exception import LangDetectException
    LANGDETECT_AVAILABLE = True

except ImportError:
    DetectorFactory = None
    detect = None
    LangDetectException = Exception
    LANGDETECT_AVAILABLE = False


try:
    from rapidfuzz import fuzz
    RAPIDFUZZ_AVAILABLE = True

except ImportError:
    fuzz = None
    RAPIDFUZZ_AVAILABLE = False


# Configuration de l'affichage

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 140)


# Configuration générale de l'audit

SEED = 42
SFT_TARGET_SIZE = 5_000

LANGUAGE_SAMPLE_SIZE = 500

NEAR_DUPLICATE_THRESHOLD = 95
NEAR_DUPLICATE_WINDOW = 5

TOKENIZER_MODEL = "Qwen/Qwen3-1.7B-Base"

RUN_TOKEN_AUDIT = True
RUN_NEAR_DUPLICATES = True


# Configuration de la reproductibilité

random.seed(SEED)
np.random.seed(SEED)

if LANGDETECT_AVAILABLE:
    DetectorFactory.seed = SEED

In [2]:
def find_project_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()

    for candidate in [start, *start.parents]:
        if (candidate / "data" / "raw").exists():
            return candidate

    raise FileNotFoundError(
        "Répertoire data/raw introuvable. Exécuter le notebook depuis le projet "
        "medical_triage_agent ou adapter PROJECT_ROOT."
    )


# Chemins du projet

PROJECT_ROOT = find_project_root()
RAW_DIR = PROJECT_ROOT / "data" / "raw"
AUDIT_DIR = PROJECT_ROOT / "data" / "audits_optimized"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)


# Registre des sources

SOURCE_REGISTRY = {
    "FrenchMedMCQA": {
        "repository": "qanastek/frenchmedmcqa", "language": "fr",
        "license": "Apache-2.0", "allowed_for_training": True, "usage": "SFT",
    },
    "MediQAl": {
        "repository": "ANR-MALADES/MediQAl", "language": "fr",
        "license": "CC-BY-4.0", "allowed_for_training": True, "usage": "SFT/EVALUATION",
    },
    "MedQuad-KV": {
        "repository": "keivalya/MedQuad-MedicalQnADataset", "language": "en",
        "license": None, "allowed_for_training": None, "usage": "SFT_REVIEW",
    },
    "UltraMedical-Preference": {
        "repository": "TsinghuaC3I/UltraMedical-Preference", "language": "en",
        "license": "MIT", "allowed_for_training": True, "usage": "DPO",
    },
}


# Datasets à auditer

DATASET_SPECS = {
    # FrenchMedMCQA
    "fmmcqa_train":      {"path": "frenchmedmcqa/train.json", "source": "FrenchMedMCQA", "split": "train",      "family": "qcm_fmm", "usage": "SFT_CANDIDATE",  "id_col": "id"},
    "fmmcqa_validation": {"path": "frenchmedmcqa/dev.json",   "source": "FrenchMedMCQA", "split": "validation", "family": "qcm_fmm", "usage": "SFT_VALIDATION", "id_col": "id"},
    "fmmcqa_test":       {"path": "frenchmedmcqa/test.json",  "source": "FrenchMedMCQA", "split": "test",       "family": "qcm_fmm", "usage": "EVALUATION",     "id_col": "id"},

    # MedQuAD
    "mquad": {"path": "medquad/medDataset_processed.csv", "source": "MedQuad-KV", "split": "unsplit", "family": "open_qa", "usage": "SFT_REVIEW", "id_col": None},

    # MediQAl - MCQM
    "mqal_mcqm_train":      {"path": "mediqal/mcqm/train.json",      "source": "MediQAl", "split": "train",      "family": "qcm_mcqm", "usage": "SFT_CANDIDATE",  "id_col": "id"},
    "mqal_mcqm_validation": {"path": "mediqal/mcqm/validation.json", "source": "MediQAl", "split": "validation", "family": "qcm_mcqm", "usage": "SFT_VALIDATION", "id_col": "id"},
    "mqal_mcqm_test":       {"path": "mediqal/mcqm/test.json",       "source": "MediQAl", "split": "test",       "family": "qcm_mcqm", "usage": "EVALUATION",     "id_col": "id"},

    # MediQAl - MCQU
    "mqal_mcqu_train":      {"path": "mediqal/mcqu/train.json",      "source": "MediQAl", "split": "train",      "family": "qcm_mcqu", "usage": "SFT_CANDIDATE",  "id_col": "id"},
    "mqal_mcqu_validation": {"path": "mediqal/mcqu/validation.json", "source": "MediQAl", "split": "validation", "family": "qcm_mcqu", "usage": "SFT_VALIDATION", "id_col": "id"},
    "mqal_mcqu_test":       {"path": "mediqal/mcqu/test.json",       "source": "MediQAl", "split": "test",       "family": "qcm_mcqu", "usage": "EVALUATION",     "id_col": "id"},

    # MediQAl - OEQ
    "mqal_oeq_test": {"path": "mediqal/oeq/test.json", "source": "MediQAl", "split": "test", "family": "open_oeq", "usage": "EVALUATION", "id_col": "id"},

    # UltraMedical Preference
    "umed_train":      {"path": "ultramedical_preference/data/train.json", "source": "UltraMedical-Preference", "split": "train",      "family": "dpo", "usage": "DPO_CANDIDATE",  "id_col": "prompt_id"},
    "umed_validation": {"path": "ultramedical_preference/data/dev.json",   "source": "UltraMedical-Preference", "split": "validation", "family": "dpo", "usage": "DPO_VALIDATION", "id_col": "prompt_id"},
    "umed_test":       {"path": "ultramedical_preference/data/test.json",  "source": "UltraMedical-Preference", "split": "test",       "family": "dpo", "usage": "EVALUATION",     "id_col": "prompt_id"},
}

# Colonnes minimales par famille
# Colonnes dont la valeur est obligatoire par famille

# Complète le contrôle de schéma par un contrôle des valeurs manquantes.
# Seuls les champs indispensables au contenu de chaque famille sont exigés.
REQUIRED_VALUE_COLUMNS = {
    "qcm_fmm": {"question", "answers", "correct_answers"},
    "qcm_mcqm": {"question", "answer_a", "answer_b", "answer_c", "answer_d", "answer_e", "correct_answers"},
    "qcm_mcqu": {"question", "answer_a", "answer_b", "answer_c", "answer_d", "answer_e", "correct_answers"},
    "open_oeq": {"question", "answer"},
    "open_qa": {"Question", "Answer"},
    "dpo": {"prompt", "chosen", "rejected"}
}

REQUIRED_COLUMNS = {
    "qcm_fmm": {"question", "answers", "correct_answers"},
    "qcm_mcqm": {"question", "answer_a", "answer_b", "answer_c", "answer_d", "answer_e", "correct_answers"},
    "qcm_mcqu": {"question", "answer_a", "answer_b", "answer_c", "answer_d", "answer_e", "correct_answers"},
    "open_oeq": {"question", "answer"},
    "open_qa": {"Question", "Answer"},
    "dpo": {"prompt", "chosen", "rejected"}
}
# Affichage du registre des sources

display(pd.DataFrame(SOURCE_REGISTRY).T.rename_axis("source").reset_index())

,source,repository,language,license,allowed_for_training,usage
0,FrenchMedMCQA,qanastek/frenchmedmcqa,fr,Apache-2.0,True,SFT
1,MediQAl,ANR-MALADES/MediQAl,fr,CC-BY-4.0,True,SFT/EVALUATION
2,MedQuad-KV,keivalya/MedQuad-MedicalQnADataset,en,NaN,NaN,SFT_REVIEW
3,UltraMedical-Preference,TsinghuaC3I/UltraMedical-Preference,en,MIT,True,DPO

<h2 style="color:#48C9B0;">2. Chargement et table canonique d’audit</h2>

<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
  <strong>Objectif :</strong><br/>
  Charger et contrôler les fichiers sources, puis construire une représentation commune permettant d’auditer de manière homogène des datasets aux structures différentes, sans modifier les données d’origine.
</div>

<p>
  Les corpus sélectionnés présentent des formats hétérogènes : QCM à réponse unique ou multiple, questions-réponses ouvertes, cas cliniques et paires de préférences DPO.
  
  Avant de pouvoir les comparer et leur appliquer les mêmes contrôles, je commence donc par charger chaque fichier dans son format natif et par vérifier sa disponibilité. Les données sont ensuite projetées dans une <strong>table canonique d’audit</strong> qui rassemble, sous des champs communs, les informations nécessaires aux analyses suivantes : source, split, type de tâche, question, contexte, réponse attendue, réponses préférée et rejetée, métadonnées et identifiants de traçabilité.
  
  Cette représentation constitue une couche d’observation commune et ne remplace pas les données sources : les DataFrames originaux restent conservés afin de pouvoir contrôler à tout moment les schémas, les types et les valeurs tels qu’ils existent dans les fichiers bruts.
</p>

In [3]:
# Chargement

# Charge CSV, JSON ou JSONL selon l'extension.
# Le JSON est relu en JSONL si nécessaire.
def load_dataset(path: Path) -> pd.DataFrame:
    """Charge un dataset tabulaire."""
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)

    if path.suffix.lower() in {".json", ".jsonl"}:
        try:
            return pd.read_json(path)
        except ValueError:
            return pd.read_json(path, lines=True)

    raise ValueError(f"Format non géré : {path.suffix}")


# Validation

# Vérifie les colonnes requises selon la famille du dataset.
# L'identifiant source est ajouté au contrôle lorsqu'il existe.
def validate_schema(name: str, df: pd.DataFrame) -> None:
    """Valide le schéma source."""
    spec = DATASET_SPECS[name]
    required = set(REQUIRED_COLUMNS[spec["family"]])

    if spec["id_col"]:
        required.add(spec["id_col"])

    missing = sorted(required - set(df.columns))

    if missing:
        raise ValueError(f"{name} : colonnes absentes : {missing}")


# Fichiers sources

# Résout les chemins et bloque immédiatement si un fichier manque.
# Aucun dataset n'est chargé avant validation de leur présence.
paths = {
    name: RAW_DIR / spec["path"]
    for name, spec in DATASET_SPECS.items()
}

missing = [str(path) for path in paths.values() if not path.exists()]

if missing:
    raise FileNotFoundError("Fichiers manquants :\n- " + "\n- ".join(missing))


# Chargement et contrôle

# Charge tous les datasets puis valide leur schéma source.
# Les volumes bruts sont conservés pour la traçabilité.
datasets = {
    name: load_dataset(path)
    for name, path in paths.items()
}

for name, df in datasets.items():
    validate_schema(name, df)

raw_row_counts = {
    name: len(df)
    for name, df in datasets.items()
}

display(
    pd.DataFrame(
        raw_row_counts.items(),
        columns=["dataset", "rows"]
    )
)

                 dataset    rows
0           fmmcqa_train    2171
1      fmmcqa_validation     312
2            fmmcqa_test     622
3                  mquad   16407
4        mqal_mcqm_train    5767
5   mqal_mcqm_validation    1466
6         mqal_mcqm_test    3384
7        mqal_mcqu_train   10113
8   mqal_mcqu_validation    2561
9         mqal_mcqu_test    4343
10         mqal_oeq_test    4969
11            umed_train  109353
12       umed_validation    2232
13             umed_test     777

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  Le chargement confirme la disponibilité de l’ensemble des fichiers attendus. 
  
  Les volumes sont très hétérogènes selon les sources : <strong>UltraMedical-Preference</strong> constitue de loin le corpus le plus volumineux, tandis que <strong>FrenchMedMCQA</strong> est plus restreint. <strong>MediQAl</strong> est réparti entre plusieurs formats et splits, et <strong>MedQuAD</strong> fournit un corpus intermédiaire de <strong>16 407 exemples</strong>. 
  
  Cette diversité de volumes devra être prise en compte lors de la sélection des données afin d’éviter qu’une source ne domine excessivement les datasets finaux.
</div>

In [4]:
# Valeurs et texte

# Détecte les valeurs absentes puis convertit proprement toute valeur en texte.
# Les structures sont sérialisées de façon stable pour garantir la reproductibilité.
def is_missing(value) -> bool:
    return (
        value is None
        or isinstance(value, float) and pd.isna(value)
        or isinstance(value, str) and value.strip().lower() in {"", "nan", "none", "null"}
    )


def text_value(value) -> str:
    if is_missing(value):
        return ""
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
    return str(value).strip()


# Audit des valeurs requises

# Compte les valeurs absentes dans les colonnes obligatoires de chaque famille.
# Le taux permet de mesurer rapidement la complétude des sources.
def required_value_audit(datasets: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Audite les valeurs requises."""
    rows = []

    for name, df in datasets.items():
        required = REQUIRED_COLUMNS[DATASET_SPECS[name]["family"]]

        for column in sorted(required):
            missing = int(df[column].map(is_missing).sum())
            rows.append({
                "dataset": name,
                "column": column,
                "missing": missing,
                "missing_rate_pct": round(missing / len(df) * 100, 2)
            })

    return pd.DataFrame(rows)


# Normalisation et hash

# Normalise le texte pour les comparaisons et génère des identifiants reproductibles.
# Les accents, espaces et éventuellement la ponctuation sont neutralisés.
def normalize_text(value, *, remove_punctuation: bool = False) -> str:
    text = unicodedata.normalize("NFKD", text_value(value).lower())
    text = "".join(c for c in text if not unicodedata.combining(c))

    if remove_punctuation:
        text = re.sub(r"[^\w\s]", " ", text)

    return re.sub(r"\s+", " ", text).strip()


def stable_hash(*values) -> str:
    payload = "\u241f".join(normalize_text(value) for value in values)
    return hashlib.sha256(payload.encode()).hexdigest()


# Réponses QCM

# Extrait les positions A-E et harmonise les choix FrenchMedMCQA / MediQAl.
# Les réponses invalides ou absentes sont ignorées.
def extract_positions(value) -> list[str]:
    if is_missing(value):
        return []

    if isinstance(value, str):
        try:
            value = ast.literal_eval(value)
        except (ValueError, SyntaxError):
            pass

    items = value if isinstance(value, (list, tuple, set)) else [value]
    positions = []

    for item in items:
        compact = re.sub(r"[^A-E]", "", str(item).upper())
        if 0 < len(compact) <= 5:
            positions.extend(compact)

    return list(dict.fromkeys(positions))


def fmm_choices(row: pd.Series) -> dict[str, str]:
    value = row.get("answers")

    if isinstance(value, dict):
        choices = {str(k).upper(): text_value(v) for k, v in value.items()}
        return {key: choices[key] for key in "ABCDE" if choices.get(key)}

    if isinstance(value, (list, tuple)):
        return {key: text_value(value) for key, value in zip("ABCDE", value)}

    return {}


def mediqal_choices(row: pd.Series) -> dict[str, str]:
    return {
        key.upper(): text_value(row.get(f"answer_{key}"))
        for key in "abcde"
        if text_value(row.get(f"answer_{key}"))
    }


# Réponse assistant

# Extrait la dernière réponse assistant depuis les formats texte, dictionnaire ou chat.
# Les autres formats sont convertis proprement en texte.
def extract_assistant_text(value) -> str:
    if isinstance(value, str):
        return value.strip()

    if isinstance(value, dict):
        return text_value(value.get("content", value))

    if isinstance(value, list):
        answers = [
            text_value(item.get("content"))
            for item in value
            if isinstance(item, dict) and item.get("role") == "assistant"
        ]
        if answers:
            return answers[-1]

    return text_value(value)


# Construction QCM

# Assemble contexte, question et choix dans un texte homogène.
# Le contexte est omis lorsqu'il est absent.
def render_qcm(context: str, question: str, choices: dict[str, str]) -> str:
    parts = [context, "", question] if context else [question]
    parts.extend(f"{key}. {value}" for key, value in choices.items())
    return "\n".join(parts).strip()

In [5]:
# Canonisation

# Convertit chaque format source vers un schéma canonique commun.
# Les règles propres à chaque famille restent explicites et auditables.
def canonical_record(dataset_name: str, row_index, row: pd.Series) -> dict:
    spec = DATASET_SPECS[dataset_name]
    source, family = spec["source"], spec["family"]

    source_id = (
        text_value(row.get(spec["id_col"]))
        if spec["id_col"]
        else f"{dataset_name}:{row_index}"
    )

    question = context = target = chosen = rejected = ""
    subject = question_type = label_type = ""
    choices, positions = {}, []
    declared_correct_count = None
    metadata = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}

    if family == "qcm_fmm":
        question = text_value(row.get("question"))
        choices = fmm_choices(row)
        positions = extract_positions(row.get("correct_answers"))
        target = ",".join(positions)
        subject = text_value(row.get("subject_name"))
        question_type = text_value(row.get("type"))
        declared_correct_count = row.get("nbr_correct_answers")
        input_text = render_qcm("", question, choices)
        group_text, task_type = input_text, "QCM"

    elif family in {"qcm_mcqm", "qcm_mcqu"}:
        context = text_value(row.get("clinical_case"))
        question = text_value(row.get("question"))
        choices = mediqal_choices(row)
        positions = extract_positions(row.get("correct_answers"))
        target = ",".join(positions)
        subject = text_value(row.get("medical_subject"))
        question_type = text_value(row.get("question_type"))
        input_text = render_qcm(context, question, choices)
        group_text = context or input_text
        task_type = "MCQM" if family == "qcm_mcqm" else "MCQU"

    elif family == "open_oeq":
        context = text_value(row.get("clinical_case"))
        question = text_value(row.get("question"))
        target = text_value(row.get("answer"))
        subject = text_value(row.get("medical_subject"))
        question_type = text_value(row.get("question_type"))
        input_text = "\n\n".join(filter(None, [context, question]))
        group_text, task_type = context or question, "OPEN_QA"

    elif family == "open_qa":
        question = text_value(row.get("Question"))
        target = text_value(row.get("Answer"))
        question_type = text_value(row.get("qtype"))
        input_text = group_text = question
        task_type = "OPEN_QA"

    elif family == "dpo":
        question = text_value(row.get("prompt"))
        chosen = extract_assistant_text(row.get("chosen"))
        rejected = extract_assistant_text(row.get("rejected"))
        label_type = text_value(row.get("label_type"))
        input_text = group_text = question
        task_type = "DPO"

    else:
        raise ValueError(f"Famille non gérée : {family}")

    # Enregistrement canonique

    # Construit le texte complet et un identifiant stable pour chaque source.
    # Le schéma commun conserve les informations nécessaires aux audits suivants.
    full_text = "\n\n".join(
        filter(None, [input_text, target, chosen, rejected])
    )

    return {
        "id": stable_hash(dataset_name, row_index, source_id)[:24],
        "dataset": dataset_name,
        "source": source,
        "source_id": source_id,
        "source_index": row_index,
        "split": spec["split"],
        "family": family,
        "usage": spec["usage"],
        "expected_language": SOURCE_REGISTRY[source]["language"],
        "allowed_for_training": SOURCE_REGISTRY[source]["allowed_for_training"],
        "task_type": task_type,
        "question_text": question,
        "context_text": context,
        "input_text": input_text,
        "target_text": target,
        "chosen_text": chosen,
        "rejected_text": rejected,
        "full_text": full_text,
        "group_text": group_text,
        "choices": choices,
        "correct_positions": positions,
        "declared_correct_count": declared_correct_count,
        "medical_subject": subject,
        "question_type": question_type,
        "label_type": label_type,
        "metadata": metadata,
        "has_context": bool(context)
    }


# Table canonique

# Canonise tous les datasets dans une table d'audit unique.
# L'unicité des identifiants garantit une ligne traçable par source.
audit_records = pd.DataFrame([
    canonical_record(name, index, row)
    for name, df in datasets.items()
    for index, row in df.iterrows()
])

if not audit_records["id"].is_unique:
    raise ValueError("Identifiants canoniques dupliqués.")

display(
    audit_records
    .groupby(["source", "split", "task_type"])
    .size()
    .rename("rows")
    .reset_index()
)

                     source       split task_type    rows
0             FrenchMedMCQA        test       QCM     622
1             FrenchMedMCQA       train       QCM    2171
2             FrenchMedMCQA  validation       QCM     312
3                MedQuad-KV     unsplit   OPEN_QA   16407
4                   MediQAl        test      MCQM    3384
5                   MediQAl        test      MCQU    4343
6                   MediQAl        test   OPEN_QA    4969
7                   MediQAl       train      MCQM    5767
8                   MediQAl       train      MCQU   10113
9                   MediQAl  validation      MCQM    1466
10                  MediQAl  validation      MCQU    2561
11  UltraMedical-Preference        test       DPO     777
12  UltraMedical-Preference       train       DPO  109353
13  UltraMedical-Preference  validation       DPO    2232

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">
  
  La table canonique restitue correctement la répartition des données par <strong>source</strong>, <strong>split</strong> et <strong>type de tâche</strong>.
  
  <strong>FrenchMedMCQA</strong> est exclusivement constitué de QCM, <strong>MediQAl</strong> combine MCQU, MCQM et questions ouvertes, <strong>MedQuad-KV</strong> apporte des questions-réponses ouvertes sans split d’origine, tandis qu’<strong>UltraMedical-Preference</strong> fournit les données DPO.
  
  Cette représentation commune permet désormais d’appliquer les mêmes contrôles d’audit à l’ensemble des corpus tout en conservant leurs spécificités.
</div>

<h2 style="color:#48C9B0;">3. Audit structurel</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Contrôler les schémas, les valeurs manquantes, les identifiants, les différences entre splits et les types internes.
</div>


<p>L’audit original montre que les données sont techniquement exploitables. Les valeurs manquantes sont concentrées dans MediQAl, surtout <code>clinical_case</code> avec environ 54 % à 63 % d’absence dans les QCM. Cette absence peut être structurelle et ne justifie aucune suppression automatique.</p>

In [6]:
# Valeurs essentielles

# Mesure les valeurs absentes dans les champs indispensables de chaque famille.
# Le rapport distingue ainsi les manques critiques des colonnes simplement optionnelles.
def required_value_audit(datasets: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Audite les valeurs essentielles."""
    rows = []

    for name, df in datasets.items():
        family = DATASET_SPECS[name]["family"]

        for column in sorted(REQUIRED_VALUE_COLUMNS[family]):
            missing = int(df[column].map(is_missing).sum())
            rows.append({
                "dataset": name,
                "column": column,
                "missing": missing,
                "missing_rate_pct": round(missing / len(df) * 100, 2)
            })

    return pd.DataFrame(rows)


# Audit structurel

# Contrôle schémas, valeurs manquantes, types internes et identifiants sources.
# Compare également les colonnes des différents splits d'une même source.
def structural_audit(datasets: dict[str, pd.DataFrame]) -> dict[str, pd.DataFrame]:
    """Audite la structure des datasets."""
    schema, missing, identifiers, types = [], [], [], []

    for name, df in datasets.items():
        spec = DATASET_SPECS[name]

        schema.append({
            "dataset": name,
            "source": spec["source"],
            "split": spec["split"],
            "rows": len(df),
            "columns": len(df.columns),
            "column_names": list(df.columns)
        })

        for column in df.columns:
            count = int(df[column].map(is_missing).sum())

            if count:
                missing.append({
                    "dataset": name,
                    "column": column,
                    "missing": count,
                    "missing_rate_pct": round(count / len(df) * 100, 2)
                })

            type_counts = (
                df[column]
                .dropna()
                .map(lambda value: type(value).__name__)
                .value_counts()
                .to_dict()
            )

            types.append({
                "dataset": name,
                "column": column,
                "pandas_dtype": str(df[column].dtype),
                "python_types": type_counts
            })

        id_col = spec["id_col"]

        if id_col and id_col in df.columns:
            missing_mask = df[id_col].map(is_missing)
            values = df.loc[~missing_mask, id_col]

            identifiers.append({
                "dataset": name,
                "id_column": id_col,
                "missing_ids": int(missing_mask.sum()),
                "unique_ids": int(values.nunique()),
                "repeated_id_rows": int(values.duplicated(keep=False).sum())
            })
        else:
            identifiers.append({
                "dataset": name,
                "id_column": None,
                "missing_ids": None,
                "unique_ids": None,
                "repeated_id_rows": None
            })

    # Comparaison des splits

    # Compare deux à deux les schémas des datasets provenant d'une même source.
    # Les écarts de colonnes sont conservés explicitement dans le rapport.
    splits = []

    for source in sorted({spec["source"] for spec in DATASET_SPECS.values()}):
        names = [
            name for name, spec in DATASET_SPECS.items()
            if spec["source"] == source
        ]

        for index, left in enumerate(names):
            for right in names[index + 1:]:
                left_cols = set(datasets[left].columns)
                right_cols = set(datasets[right].columns)

                splits.append({
                    "source": source,
                    "left_dataset": left,
                    "right_dataset": right,
                    "only_left": sorted(left_cols - right_cols),
                    "only_right": sorted(right_cols - left_cols),
                    "common_columns": len(left_cols & right_cols)
                })

    return {
        "03_schema": pd.DataFrame(schema),
        "03_missing_by_column": pd.DataFrame(missing),
        "03_identifiers": pd.DataFrame(identifiers),
        "03_split_schema_differences": pd.DataFrame(splits),
        "03_internal_types": pd.DataFrame(types)
    }


# Exécution

# Exécute les audits structurels et ajoute le contrôle des valeurs essentielles.
# Les rapports sont centralisés pour leur affichage et leur export ultérieur.
REPORTS = structural_audit(datasets)
REPORTS["03_required_values"] = required_value_audit(datasets)

for name in [
    "03_schema",
    "03_missing_by_column",
    "03_required_values",
    "03_identifiers",
    "03_split_schema_differences"
]:
    print(name)
    display(REPORTS[name])

03_schema

,dataset,source,split,rows,columns,column_names
0,fmmcqa_train,FrenchMedMCQA,train,2171,7,"[id, question, answers, correct_answers, subject_name, type, nbr_correct_answers]"
1,fmmcqa_validation,FrenchMedMCQA,validation,312,7,"[id, question, answers, correct_answers, subject_name, type, nbr_correct_answers]"
2,fmmcqa_test,FrenchMedMCQA,test,622,6,"[id, question, answers, correct_answers, subject_name, nbr_correct_answers]"
3,mquad,MedQuad-KV,unsplit,16407,3,"[qtype, Question, Answer]"
4,mqal_mcqm_train,MediQAl,train,5767,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
5,mqal_mcqm_validation,MediQAl,validation,1466,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
6,mqal_mcqm_test,MediQAl,test,3384,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
7,mqal_mcqu_train,MediQAl,train,10113,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
8,mqal_mcqu_validation,MediQAl,validation,2561,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
9,mqal_mcqu_test,MediQAl,test,4343,12,"[id, clinical_case, question, answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task, medical_subject, question_type]"
10,mqal_oeq_test,MediQAl,test,4969,7,"[id, clinical_case, cc_question_number, question, answer, medical_subject, question_type]"
11,umed_train,UltraMedical-Preference,train,109353,7,"[prompt_id, label_type, prompt, chosen, rejected, metadata, feedback]"
12,umed_validation,UltraMedical-Preference,validation,2232,7,"[prompt_id, label_type, prompt, chosen, rejected, metadata, feedback]"
13,umed_test,UltraMedical-Preference,test,777,6,"[prompt_id, label_type, prompt, chosen, rejected, metadata]"

03_missing_by_column

                dataset              column  missing  missing_rate_pct
0       mqal_mcqm_train       clinical_case     3582             62.11
1  mqal_mcqm_validation       clinical_case      919             62.69
2        mqal_mcqm_test       clinical_case     2042             60.34
3       mqal_mcqu_train       clinical_case     6178             61.09
4       mqal_mcqu_train            answer_e        2              0.02
5  mqal_mcqu_validation       clinical_case     1562             60.99
6  mqal_mcqu_validation            answer_e        1              0.04
7        mqal_mcqu_test       clinical_case     2347             54.04
8         mqal_oeq_test       clinical_case     1015             20.43
9         mqal_oeq_test  cc_question_number     1016             20.45

03_required_values

              dataset           column  missing  missing_rate_pct
0        fmmcqa_train          answers        0               0.0
1        fmmcqa_train  correct_answers        0               0.0
2        fmmcqa_train         question        0               0.0
3   fmmcqa_validation          answers        0               0.0
4   fmmcqa_validation  correct_answers        0               0.0
..                ...              ...      ...               ...
59    umed_validation           prompt        0               0.0
60    umed_validation         rejected        0               0.0
61          umed_test           chosen        0               0.0
62          umed_test           prompt        0               0.0
63          umed_test         rejected        0               0.0

[64 rows x 4 columns]

03_identifiers

                 dataset  id_column  missing_ids  unique_ids  repeated_id_rows
0           fmmcqa_train         id          0.0      2170.0               2.0
1      fmmcqa_validation         id          0.0       312.0               0.0
2            fmmcqa_test         id          0.0       622.0               0.0
3                  mquad        NaN          NaN         NaN               NaN
4        mqal_mcqm_train         id          0.0      5767.0               0.0
5   mqal_mcqm_validation         id          0.0      1466.0               0.0
6         mqal_mcqm_test         id          0.0      3384.0               0.0
7        mqal_mcqu_train         id          0.0     10113.0               0.0
8   mqal_mcqu_validation         id          0.0      2561.0               0.0
9         mqal_mcqu_test         id          0.0      4343.0               0.0
10         mqal_oeq_test         id          0.0      4969.0               0.0
11            umed_train  prompt_id          0.0     77046.0           59229.0
12       umed_validation  prompt_id          0.0      2215.0              33.0
13             umed_test  prompt_id          0.0       776.0               2.0

03_split_schema_differences

,source,left_dataset,right_dataset,only_left,only_right,common_columns
0,FrenchMedMCQA,fmmcqa_train,fmmcqa_validation,[],[],7
1,FrenchMedMCQA,fmmcqa_train,fmmcqa_test,[type],[],6
2,FrenchMedMCQA,fmmcqa_validation,fmmcqa_test,[type],[],6
3,MediQAl,mqal_mcqm_train,mqal_mcqm_validation,[],[],12
4,MediQAl,mqal_mcqm_train,mqal_mcqm_test,[],[],12
5,MediQAl,mqal_mcqm_train,mqal_mcqu_train,[],[],12
6,MediQAl,mqal_mcqm_train,mqal_mcqu_validation,[],[],12
7,MediQAl,mqal_mcqm_train,mqal_mcqu_test,[],[],12
8,MediQAl,mqal_mcqm_train,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
9,MediQAl,mqal_mcqm_validation,mqal_mcqm_test,[],[],12
10,MediQAl,mqal_mcqm_validation,mqal_mcqu_train,[],[],12
11,MediQAl,mqal_mcqm_validation,mqal_mcqu_validation,[],[],12
12,MediQAl,mqal_mcqm_validation,mqal_mcqu_test,[],[],12
13,MediQAl,mqal_mcqm_validation,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
14,MediQAl,mqal_mcqm_test,mqal_mcqu_train,[],[],12
15,MediQAl,mqal_mcqm_test,mqal_mcqu_validation,[],[],12
16,MediQAl,mqal_mcqm_test,mqal_mcqu_test,[],[],12
17,MediQAl,mqal_mcqm_test,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
18,MediQAl,mqal_mcqu_train,mqal_mcqu_validation,[],[],12
19,MediQAl,mqal_mcqu_train,mqal_mcqu_test,[],[],12
20,MediQAl,mqal_mcqu_train,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
21,MediQAl,mqal_mcqu_validation,mqal_mcqu_test,[],[],12
22,MediQAl,mqal_mcqu_validation,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
23,MediQAl,mqal_mcqu_test,mqal_oeq_test,"[answer_a, answer_b, answer_c, answer_d, answer_e, correct_answers, task]","[answer, cc_question_number]",5
24,UltraMedical-Preference,umed_train,umed_validation,[],[],7
25,UltraMedical-Preference,umed_train,umed_test,[feedback],[],6
26,UltraMedical-Preference,umed_validation,umed_test,[feedback],[],6

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit structurel confirme que les corpus sont globalement cohérents avec leur documentation, mais met en évidence plusieurs particularités : 
  </p>

  <p>
    <strong>Pour la structure des fichiers :</strong> 
    <ul>
      <li>
        les splits <code>train</code>,<code>validation</code> et <code>test</code> de <strong>MediQAl MCQM/MCQU</strong>
        présentent un schéma homogène de 12 colonnes. 
      </li>
      <li>
        Les différences observées avec <strong>MediQAl OEQ</strong> sont normales puisqu’il s’agit d’un autre type de tâche,
        basé sur une réponse ouverte plutôt que sur des choix A-E.
      </li>
      <li>
        <strong>FrenchMedMCQA</strong> présente une différence mineure : la colonne <code>type</code> est absente du split <code>test</code>.
      <li>
      De même, la colonne <code>feedback</code> d’<strong>UltraMedical-Preference</strong>
      est absente du split <code>test</code>.
      </li>
    </ul>
  </p>

  <p>
    <strong>Valeurs manquantes :</strong> elles concernent principalement
    <code>clinical_case</code> dans <strong>MediQAl</strong>. Plus de la moitié des
    exemples MCQM et MCQU ne possèdent pas de cas clinique, avec des taux compris
    entre environ <strong>54 % et 63 %</strong>. Cette absence ne doit pas être
    considérée automatiquement comme une anomalie : certaines questions sont autonomes
    et ne nécessitent pas de contexte clinique. Pour OEQ, environ <strong>20 %</strong>
    des valeurs de <code>clinical_case</code> et <code>cc_question_number</code>
    sont absentes.
  </p>

  <p>
    <strong>Identifiants :</strong> MediQAl ne présente aucun identifiant manquant
    ou répété dans les différents sous-ensembles analysés. FrenchMedMCQA contient
    toutefois <strong>2 lignes associées à un identifiant répété dans le train</strong>,
    qui devront être examinées. MedQuad-KV ne possède pas d’identifiant source explicite
    et nécessitera donc la génération d’un identifiant interne stable pour assurer
    sa traçabilité.
  </p>

  <p>
    <strong>UltraMedical-Preference :</strong> le split train contient
    <strong>109 353 lignes pour 77 046 prompt_id uniques</strong>, avec
    <strong>59 229 lignes appartenant à des identifiants répétés</strong>.
    Ces répétitions ne doivent pas être supprimées sur le seul critère du
    <code>prompt_id</code>, puisqu’un même prompt peut être associé à plusieurs couples
    de réponses ou préférences. Leur validité devra être déterminée par l’audit DPO
    des triplets <code>prompt / chosen / rejected</code>.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>ne pas supprimer automatiquement les exemples MediQAl dont <code>clinical_case</code> est absent ; vérifier d’abord si la question est autonome ;</li>
    <li>examiner les identifiants répétés de <strong>FrenchMedMCQA train</strong> avant toute suppression ;</li>
    <li>générer un identifiant stable pour <strong>MedQuad-KV</strong> afin de garantir la traçabilité ;</li>
    <li>ne pas utiliser les répétitions de <code>prompt_id</code> comme critère de déduplication DPO ; utiliser le contenu du prompt et des réponses ;</li>
    <li>harmoniser les différences de colonnes entre les splits dans la représentation finale sans modifier les fichiers sources ;</li>
    <li>traiter séparément <strong>MediQAl OEQ</strong> des formats MCQU/MCQM en raison de sa structure et de son usage différents.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">4. Audit des QCM</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Vérifier le nombre de propositions, l’encodage des réponses, le mode unique ou multiple, la validité des positions et les biais de réponse.
</div>


<p>FrenchMedMCQA et MediQAl MCQM utilisent cinq propositions. Trois questions MCQU n’en ont que quatre et doivent être conservées sans inventer une cinquième option. Les positions sont structurellement valides ; MediQAl MCQU présente toutefois un déséquilibre plus marqué, avec C surreprésenté dans train et validation.</p>

In [7]:
# Contrôle QCM

# Vérifie le nombre de choix, les positions correctes et le mode MCQU / MCQM.
# Contrôle aussi la cohérence avec le nombre de réponses déclaré par la source.
qcm = audit_records[
    audit_records["family"].isin({"qcm_fmm", "qcm_mcqm", "qcm_mcqu"})
].copy()

qcm["choice_count"] = qcm["choices"].map(len)
qcm["correct_count"] = qcm["correct_positions"].map(len)

qcm["invalid_positions"] = qcm.apply(
    lambda row: [
        pos for pos in row["correct_positions"]
        if pos not in row["choices"]
    ],
    axis=1
)

qcm["valid_answer_positions"] = qcm["invalid_positions"].map(len).eq(0)

qcm["valid_mode"] = qcm.apply(
    lambda row:
        row["correct_count"] == 1 if row["family"] == "qcm_mcqu"
        else row["correct_count"] >= 2 if row["family"] == "qcm_mcqm"
        else row["correct_count"] >= 1,
    axis=1
)

qcm["declared_count_match"] = qcm.apply(
    lambda row:
        True if is_missing(row["declared_correct_count"])
        else int(row["declared_correct_count"]) == row["correct_count"],
    axis=1
)


# Synthèse

# Agrège les anomalies QCM par dataset pour mesurer leur qualité structurelle.
# Les erreurs de position, de mode et de comptage restent distinguées.
qcm_summary = (
    qcm.groupby("dataset")
    .agg(
        rows=("id", "size"),
        min_choices=("choice_count", "min"),
        max_choices=("choice_count", "max"),
        min_correct=("correct_count", "min"),
        max_correct=("correct_count", "max"),
        invalid_position_rows=("valid_answer_positions", lambda x: int((~x).sum())),
        invalid_mode_rows=("valid_mode", lambda x: int((~x).sum())),
        declared_count_mismatches=("declared_count_match", lambda x: int((~x).sum()))
    )
    .reset_index()
)


# Distribution des réponses

# Mesure la fréquence des positions correctes A-E pour détecter un éventuel biais.
# Les taux sont calculés indépendamment pour chaque dataset.
position_distribution = (
    qcm[["dataset", "correct_positions"]]
    .explode("correct_positions")
    .dropna()
    .groupby(["dataset", "correct_positions"])
    .size()
    .rename("count")
    .reset_index()
)

position_distribution["rate_pct"] = (
    position_distribution["count"]
    / position_distribution.groupby("dataset")["count"].transform("sum")
    * 100
).round(2)


# Rapports

# Enregistre les résultats dans le registre commun puis affiche leur synthèse.
# La vue pivot facilite la comparaison des positions A-E entre datasets.
REPORTS["04_qcm_summary"] = qcm_summary
REPORTS["04_qcm_position_distribution"] = position_distribution

display(qcm_summary)

display(
    position_distribution
    .pivot(
        index="dataset",
        columns="correct_positions",
        values="rate_pct"
    )
    .fillna(0)
)

,dataset,rows,min_choices,max_choices,min_correct,max_correct,invalid_position_rows,invalid_mode_rows,declared_count_mismatches
0,fmmcqa_test,622,5,5,1,5,0,0,0
1,fmmcqa_train,2171,5,5,1,5,0,0,0
2,fmmcqa_validation,312,5,5,1,5,0,0,0
3,mqal_mcqm_test,3384,5,5,2,5,0,0,0
4,mqal_mcqm_train,5767,5,5,2,5,0,0,0
5,mqal_mcqm_validation,1466,5,5,2,5,0,0,0
6,mqal_mcqu_test,4343,5,5,1,1,0,0,0
7,mqal_mcqu_train,10113,4,5,1,1,0,0,0
8,mqal_mcqu_validation,2561,4,5,1,1,0,0,0

correct_positions         A      B      C      D      E
dataset
fmmcqa_test           19.13  19.88  22.06  21.39  17.54
fmmcqa_train          20.12  20.72  20.60  20.66  17.89
fmmcqa_validation     19.26  20.60  22.78  20.27  17.09
mqal_mcqm_test        22.34  21.21  20.82  20.10  15.53
mqal_mcqm_train       21.48  21.05  20.70  19.11  17.65
mqal_mcqm_validation  21.38  20.56  22.05  18.93  17.08
mqal_mcqu_test        19.78  23.72  21.00  19.59  15.91
mqal_mcqu_train       12.37  20.09  26.90  23.82  16.82
mqal_mcqu_validation  12.26  18.74  26.51  24.83  17.65

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit des QCM montre une <strong>bonne cohérence structurelle globale</strong>. Toutes les réponses correctes correspondent à des positions valides, aucun exemple ne présente un nombre de réponses correctes incompatible avec son type de QCM et aucune incohérence n’est détectée entre le nombre de réponses déclaré et le nombre réellement extrait.
  </p>

  <p>
    <strong>FrenchMedMCQA</strong> contient systématiquement <strong>5 choix</strong> et entre <strong>1 et 5 réponses correctes</strong>, conformément à son fonctionnement. <strong>MediQAl MCQM</strong> contient également 5 choix, avec <strong>2 à 5 réponses correctes</strong>. <strong>MediQAl MCQU</strong> respecte bien la contrainte d’une <strong>seule réponse correcte</strong>, même si certains exemples des splits train et validation ne comportent que <strong>4 choix au lieu de 5</strong>. Cette particularité devra être conservée lors de la construction des instructions plutôt que complétée artificiellement.
  </p>

  <p>
    <strong>Distribution des réponses :</strong> les positions correctes A-E sont présentes dans tous les corpus et aucun déséquilibre extrême n’apparaît. Certaines tendances sont néanmoins visibles, notamment dans <strong>MediQAl MCQU train et validation</strong>, où les positions C et D sont plus fréquentes et la position A moins représentée. La position E est également légèrement moins fréquente dans plusieurs datasets. Ces distributions devront être conservées à l’esprit lors de l’échantillonnage du dataset SFT afin de ne pas accentuer artificiellement ces biais.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>conserver les QCM validés, aucune anomalie de position ou de cardinalité ne justifiant une suppression globale ;</li>
    <li>préserver les QCM MediQAl MCQU à 4 choix sans créer artificiellement une cinquième réponse ;</li>
    <li>conserver correctement les réponses multiples de FrenchMedMCQA et MediQAl MCQM lors de leur conversion au format SFT ;</li>
    <li>ne pas rééquilibrer artificiellement les positions A-E, mais surveiller leur distribution lors de la sélection finale des exemples SFT ;</li>
    <li>maintenir la distinction entre <strong>MCQU</strong>, <strong>MCQM</strong> et les QCM FrenchMedMCQA afin que la réponse attendue soit construite selon les règles propres à chaque format.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">5. Audit textuel</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Contrôler les langues, les longueurs, les tokens, les anomalies de forme et l’autonomie des questions MediQAl.
</div>


<p>Les échantillons de l’audit original sont majoritairement conformes aux langues attendues : environ 97,2 % de français pour FrenchMedMCQA, 97,4 % pour MediQAl, 97,4 % d’anglais pour MedQuAD et 99,6 % pour UltraMedical. Les questions dépendantes MediQAl avec contexte représentent environ 3,75 % à 7,24 % selon les sous-ensembles.</p>

In [8]:
# Détection de langue

# Détecte la langue uniquement sur un texte suffisamment long et exploitable.
# Les erreurs ou l'absence de langdetect sont converties en statut unknown.
def detect_language_safe(text: str) -> str:
    if not LANGDETECT_AVAILABLE or len(text.strip()) < 20:
        return "unknown"

    try:
        return detect(text)
    except LangDetectException:
        return "unknown"


# Audit linguistique

# Échantillonne chaque dataset avec une graine fixe puis mesure les langues détectées.
# La distribution est comparée à la langue attendue déclarée dans le registre source.
language_rows = []

for name, group in audit_records.groupby("dataset", sort=False):
    sample = group.sample(
        min(LANGUAGE_SAMPLE_SIZE, len(group)),
        random_state=SEED
    )

    counts = (
        sample["input_text"]
        .map(detect_language_safe)
        .value_counts(dropna=False)
    )

    language_rows.extend({
        "dataset": name,
        "expected_language": group["expected_language"].iloc[0],
        "detected_language": language,
        "sample_rows": len(sample),
        "count": int(count),
        "rate_pct": round(count / len(sample) * 100, 2)
    } for language, count in counts.items())


# Rapport

# Enregistre la distribution linguistique dans le registre commun des audits.
# Le rapport permet de repérer les langues inattendues ou non détectées.
language_summary = pd.DataFrame(language_rows)
REPORTS["05_language_sample_distribution"] = language_summary

display(language_summary)

,dataset,expected_language,detected_language,sample_rows,count,rate_pct
0,fmmcqa_train,fr,fr,500,499,99.8
1,fmmcqa_train,fr,en,500,1,0.2
2,fmmcqa_validation,fr,fr,312,312,100.0
3,fmmcqa_test,fr,fr,500,500,100.0
4,mquad,en,en,500,487,97.4
5,mquad,en,it,500,7,1.4
6,mquad,en,ca,500,2,0.4
7,mquad,en,es,500,1,0.2
8,mquad,en,ro,500,1,0.2
9,mquad,en,sv,500,1,0.2
10,mquad,en,unknown,500,1,0.2
11,mqal_mcqm_train,fr,fr,500,500,100.0
12,mqal_mcqm_validation,fr,fr,500,500,100.0
13,mqal_mcqm_test,fr,fr,500,500,100.0
14,mqal_mcqu_train,fr,fr,500,498,99.6
15,mqal_mcqu_train,fr,ca,500,2,0.4
16,mqal_mcqu_validation,fr,fr,500,496,99.2
17,mqal_mcqu_validation,fr,ca,500,2,0.4
18,mqal_mcqu_validation,fr,pt,500,1,0.2
19,mqal_mcqu_validation,fr,en,500,1,0.2
20,mqal_mcqu_test,fr,fr,500,500,100.0
21,mqal_oeq_test,fr,fr,500,500,100.0
22,umed_train,en,en,500,498,99.6
23,umed_train,en,ro,500,2,0.4
24,umed_validation,en,en,500,496,99.2
25,umed_validation,en,ro,500,2,0.4
26,umed_validation,en,fr,500,1,0.2
27,umed_validation,en,cy,500,1,0.2
28,umed_test,en,en,500,499,99.8
29,umed_test,en,ro,500,1,0.2

In [9]:
# Longueur des textes

# Mesure la longueur en caractères et en mots des principaux champs textuels.
# Les champs vides sont exclus pour ne pas fausser les distributions.
text_fields = [
    "input_text",
    "target_text",
    "context_text",
    "chosen_text",
    "rejected_text",
    "full_text"
]

lengths = []

for field in text_fields:
    df = audit_records[["dataset", "id", field]].copy()
    df = df[df[field].astype(str).str.len().gt(0)]

    df["field"] = field
    df["char_length"] = df[field].str.len()
    df["word_length"] = df[field].str.split().str.len()

    lengths.append(
        df.drop(columns=field)
    )


# Synthèse

# Agrège médiane, P95 et maximum pour repérer les textes longs ou atypiques.
# Ces mesures serviront ensuite au contrôle des longueurs de séquence.
text_lengths = pd.concat(lengths, ignore_index=True)

text_length_summary = (
    text_lengths
    .groupby(["dataset", "field"])
    .agg(
        rows=("id", "size"),
        char_median=("char_length", "median"),
        char_p95=("char_length", lambda x: x.quantile(0.95)),
        char_max=("char_length", "max"),
        word_median=("word_length", "median"),
        word_p95=("word_length", lambda x: x.quantile(0.95)),
        word_max=("word_length", "max")
    )
    .round(2)
    .reset_index()
)


# Rapport

# Enregistre les statistiques dans le registre commun des audits.
# Le tableau permet de comparer rapidement les distributions entre sources.
REPORTS["05_text_length_summary"] = text_length_summary

display(text_length_summary)

,dataset,field,rows,char_median,char_p95,char_max,word_median,word_p95,word_max
0,fmmcqa_test,full_text,622,336.0,540.85,714,50.0,81.95,106
1,fmmcqa_test,input_text,622,332.5,533.85,710,49.0,80.95,105
2,fmmcqa_test,target_text,622,1.0,7.00,9,1.0,1.00,1
3,fmmcqa_train,full_text,2171,327.0,575.00,1304,50.0,86.00,180
4,fmmcqa_train,input_text,2171,321.0,569.00,1297,49.0,85.00,179
5,fmmcqa_train,target_text,2171,3.0,7.00,9,1.0,1.00,1
6,fmmcqa_validation,full_text,312,313.0,514.50,698,47.5,77.45,105
7,fmmcqa_validation,input_text,312,309.5,508.80,695,46.5,76.45,104
8,fmmcqa_validation,target_text,312,1.0,7.00,9,1.0,1.00,1
9,mqal_mcqm_test,context_text,1342,674.5,1263.80,2487,107.5,197.90,420
10,mqal_mcqm_test,full_text,3384,381.5,1354.40,2875,59.0,208.00,479
11,mqal_mcqm_test,input_text,3384,374.5,1345.00,2864,58.0,207.00,478
12,mqal_mcqm_test,target_text,3384,3.0,7.00,9,1.0,1.00,1
13,mqal_mcqm_train,context_text,2185,641.0,1278.00,2487,101.0,202.00,420
14,mqal_mcqm_train,full_text,5767,354.0,1360.70,2823,54.0,210.00,465
15,mqal_mcqm_train,input_text,5767,348.0,1355.00,2816,53.0,209.00,464
16,mqal_mcqm_train,target_text,5767,5.0,9.00,9,1.0,1.00,1
17,mqal_mcqm_validation,context_text,547,622.0,1215.00,2187,98.0,188.00,347
18,mqal_mcqm_validation,full_text,1466,347.5,1302.50,2468,53.0,203.00,387
19,mqal_mcqm_validation,input_text,1466,340.0,1293.75,2463,52.0,202.00,386
20,mqal_mcqm_validation,target_text,1466,5.0,9.00,9,1.0,1.00,1
21,mqal_mcqu_test,context_text,1996,578.0,1265.25,2487,89.0,198.00,420
22,mqal_mcqu_test,full_text,4343,445.0,1373.80,2793,71.0,214.90,465
23,mqal_mcqu_test,input_text,4343,442.0,1370.80,2790,70.0,213.90,464
24,mqal_mcqu_test,target_text,4343,1.0,1.00,1,1.0,1.00,1
25,mqal_mcqu_train,context_text,3935,591.0,1256.00,2487,91.0,196.00,420
26,mqal_mcqu_train,full_text,10113,371.0,1320.00,2772,58.0,206.00,464
27,mqal_mcqu_train,input_text,10113,368.0,1317.00,2769,57.0,205.00,463
28,mqal_mcqu_train,target_text,10113,1.0,1.00,1,1.0,1.00,1
29,mqal_mcqu_validation,context_text,999,574.0,1220.70,2103,90.0,188.20,290
30,mqal_mcqu_validation,full_text,2561,368.0,1286.00,2322,58.0,202.00,350
31,mqal_mcqu_validation,input_text,2561,365.0,1283.00,2319,57.0,201.00,349
32,mqal_mcqu_validation,target_text,2561,1.0,1.00,1,1.0,1.00,1
33,mqal_oeq_test,context_text,3954,749.0,1777.00,3967,116.0,284.00,614
34,mqal_oeq_test,full_text,4969,993.0,2265.20,4320,151.0,350.60,694
35,mqal_oeq_test,input_text,4969,719.0,1845.80,4021,114.0,296.60,652
36,mqal_oeq_test,target_text,4969,176.0,703.00,1020,25.0,102.00,148
37,mquad,full_text,16407,937.0,3442.10,29091,146.0,531.00,4289
38,mquad,input_text,16407,48.0,81.00,191,8.0,12.00,27
39,mquad,target_text,16407,890.0,3399.40,29046,138.0,523.00,4281
40,umed_test,chosen_text,777,2019.0,3995.20,6078,306.0,553.00,802
41,umed_test,full_text,777,3980.0,8020.80,10783,607.0,1121.40,1676
42,umed_test,input_text,777,399.0,1449.40,2532,64.0,221.20,376
43,umed_test,rejected_text,777,1461.0,3828.60,6070,223.0,535.40,1020
44,umed_train,chosen_text,109353,1937.0,4372.00,13052,293.0,598.00,1220
45,umed_train,full_text,109353,3977.0,8938.00,20770,600.0,1222.00,3247
46,umed_train,input_text,109353,402.0,1142.00,5509,59.0,184.00,1036
47,umed_train,rejected_text,109353,1569.0,4332.00,15940,239.0,592.00,2719
48,umed_validation,chosen_text,2232,1907.5,4394.45,8209,287.5,603.00,1139
49,umed_validation,full_text,2232,3930.5,8959.90,12950,597.0,1222.90,1785
50,umed_validation,input_text,2232,411.0,1171.00,4385,61.0,186.00,857
51,umed_validation,rejected_text,2232,1580.5,4306.45,7655,240.5,591.00,1030

In [10]:
# Longueur en tokens

# Tokenise les textes avec le tokenizer du modèle cible et mesure leur longueur.
# L'audit permet d'anticiper les troncatures avant SFT et DPO.
token_summary = pd.DataFrame()
token_thresholds = pd.DataFrame()

if RUN_TOKEN_AUDIT:
    try:
        from transformers import AutoTokenizer

        tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_MODEL)

        token_details = audit_records[["dataset", "id"]].copy()
        token_details["token_count"] = audit_records["full_text"].map(
            lambda text: len(tokenizer.encode(text, add_special_tokens=True))
        )

        token_summary = (
            token_details
            .groupby("dataset")["token_count"]
            .agg(
                rows="size",
                median="median",
                p95=lambda x: x.quantile(0.95),
                p99=lambda x: x.quantile(0.99),
                maximum="max"
            )
            .round(2)
            .reset_index()
        )


        # Seuils de séquence

        # Compte les textes dépassant 512, 1024 et 2048 tokens par dataset.
        # Les taux permettent d'évaluer directement le risque de troncature.
        thresholds = []

        for name, group in token_details.groupby("dataset"):
            for threshold in [512, 1024, 2048]:
                count = int(group["token_count"].gt(threshold).sum())
                thresholds.append({
                    "dataset": name,
                    "threshold": threshold,
                    "rows_above": count,
                    "rate_pct": round(count / len(group) * 100, 2)
                })

        token_thresholds = pd.DataFrame(thresholds)

    except (ImportError, OSError) as error:
        print(f"Audit des tokens non exécuté : {error}")


# Rapports

# Enregistre les distributions et dépassements dans le registre des audits.
# Les résultats servent ensuite à justifier la longueur maximale retenue.
REPORTS["05_token_length_summary"] = token_summary
REPORTS["05_token_thresholds"] = token_thresholds

display(token_summary)
display(token_thresholds)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

                 dataset    rows  median      p95      p99  maximum
0            fmmcqa_test     622   105.0   162.00   191.95      246
1           fmmcqa_train    2171   104.0   172.00   209.30      348
2      fmmcqa_validation     312   102.0   156.00   173.89      211
3         mqal_mcqm_test    3384   120.0   435.00   567.34      868
4        mqal_mcqm_train    5767   113.0   432.00   555.34      851
5   mqal_mcqm_validation    1466   112.0   423.75   526.05      848
6         mqal_mcqu_test    4343   147.0   452.90   604.00      943
7        mqal_mcqu_train   10113   123.0   433.00   577.88      844
8   mqal_mcqu_validation    2561   123.0   418.00   575.00      733
9          mqal_oeq_test    4969   302.0   741.60   963.96     1505
10                 mquad   16407   198.0   766.70  1649.94     5712
11             umed_test     777   842.0  1586.20  1891.80     2813
12            umed_train  109353   846.0  1729.00  1965.00     5984
13       umed_validation    2232   840.0  1716.00  1961.52     3073

                 dataset  threshold  rows_above  rate_pct
0            fmmcqa_test        512           0      0.00
1            fmmcqa_test       1024           0      0.00
2            fmmcqa_test       2048           0      0.00
3           fmmcqa_train        512           0      0.00
4           fmmcqa_train       1024           0      0.00
5           fmmcqa_train       2048           0      0.00
6      fmmcqa_validation        512           0      0.00
7      fmmcqa_validation       1024           0      0.00
8      fmmcqa_validation       2048           0      0.00
9         mqal_mcqm_test        512          76      2.25
10        mqal_mcqm_test       1024           0      0.00
11        mqal_mcqm_test       2048           0      0.00
12       mqal_mcqm_train        512         116      2.01
13       mqal_mcqm_train       1024           0      0.00
14       mqal_mcqm_train       2048           0      0.00
15  mqal_mcqm_validation        512          27      1.84
16  mqal_mcqm_validation       1024           0      0.00
17  mqal_mcqm_validation       2048           0      0.00
18        mqal_mcqu_test        512         118      2.72
19        mqal_mcqu_test       1024           0      0.00
20        mqal_mcqu_test       2048           0      0.00
21       mqal_mcqu_train        512         209      2.07
22       mqal_mcqu_train       1024           0      0.00
23       mqal_mcqu_train       2048           0      0.00
24  mqal_mcqu_validation        512          52      2.03
25  mqal_mcqu_validation       1024           0      0.00
26  mqal_mcqu_validation       2048           0      0.00
27         mqal_oeq_test        512        1076     21.65
28         mqal_oeq_test       1024          36      0.72
29         mqal_oeq_test       2048           0      0.00
30                 mquad        512        1936     11.80
31                 mquad       1024         431      2.63
32                 mquad       2048         114      0.69
33             umed_test        512         690     88.80
34             umed_test       1024         252     32.43
35             umed_test       2048           2      0.26
36            umed_train        512       96324     88.09
37            umed_train       1024       42682     39.03
38            umed_train       2048         585      0.53
39       umed_validation        512        1958     87.72
40       umed_validation       1024         863     38.66
41       umed_validation       2048           7      0.31

In [11]:
# Références contextuelles

# Repère les formulations FR / EN qui dépendent potentiellement d'un contexte précédent.
# Elles servent à identifier les questions MediQAl qui ne sont pas autonomes.
CONTEXT_REFERENCE_PATTERN = re.compile(
    r"\b(?:ce patient|cette patiente|ce cas|dans ce cas|ces résultats|ci-dessus|"
    r"this patient|this case|these results|above|précédent(?:e|es|s)?)\b",
    flags=re.IGNORECASE
)


# Anomalies textuelles

# Détecte les anomalies simples pouvant dégrader la qualité des exemples.
# Les signaux restent descriptifs et ne provoquent aucune suppression automatique.
def text_anomaly_flags(text: str) -> list[str]:
    """Détecte les anomalies textuelles."""
    text = text or ""
    stripped = text.strip()

    if not stripped:
        return ["EMPTY_TEXT"]

    flags = []

    if len(stripped) < 5:
        flags.append("VERY_SHORT_TEXT")
    if re.search(r"[ \t]{3,}", text):
        flags.append("EXCESSIVE_SPACES")
    if re.search(r"(.)\1{4,}", text, flags=re.IGNORECASE):
        flags.append("REPEATED_CHARACTER")
    if re.search(r"\b(\w+)\s+\1\b", text, flags=re.IGNORECASE):
        flags.append("REPEATED_WORD")

    symbol_ratio = sum(
        not char.isalnum() and not char.isspace()
        for char in text
    ) / len(text)

    if symbol_ratio > 0.30:
        flags.append("HIGH_SYMBOL_RATIO")

    return flags


# Synthèse des anomalies

# Applique les contrôles à chaque enregistrement puis agrège les signaux par dataset.
# Le détail reste disponible pour retrouver précisément les lignes concernées.
anomaly_details = audit_records[["dataset", "id", "full_text"]].copy()
anomaly_details["anomaly_flags"] = anomaly_details["full_text"].map(
    text_anomaly_flags
)
anomaly_details["has_anomaly"] = anomaly_details["anomaly_flags"].map(bool)

anomaly_summary = (
    anomaly_details
    .explode("anomaly_flags")
    .dropna(subset=["anomaly_flags"])
    .groupby(["dataset", "anomaly_flags"])
    .size()
    .rename("rows")
    .reset_index()
    .rename(columns={"anomaly_flags": "anomaly"})
)


# Autonomie MediQAl

# Recherche les questions faisant référence à un contexte clinique implicite.
# Distingue les références disposant du contexte de celles réellement orphelines.
autonomy = audit_records[
    audit_records["source"].eq("MediQAl")
].copy()

autonomy["context_reference"] = autonomy["question_text"].str.contains(
    CONTEXT_REFERENCE_PATTERN,
    regex=True,
    na=False
)

autonomy["autonomy_status"] = np.select(
    [
        autonomy["context_reference"] & autonomy["has_context"],
        autonomy["context_reference"] & ~autonomy["has_context"]
    ],
    [
        "DEPENDENT_WITH_CONTEXT",
        "DEPENDENT_WITHOUT_CONTEXT"
    ],
    default="AUTONOMOUS_OR_UNDETECTED"
)

autonomy_summary = (
    autonomy
    .groupby(["dataset", "autonomy_status"])
    .size()
    .rename("rows")
    .reset_index()
)

autonomy_summary["rate_pct"] = (
    autonomy_summary["rows"]
    / autonomy_summary.groupby("dataset")["rows"].transform("sum")
    * 100
).round(2)


# Rapports

# Archive les anomalies textuelles et les statuts d'autonomie dans le registre commun.
# Les deux rapports servent ensuite à cibler les exemples nécessitant une revue.
REPORTS["05_text_anomalies_summary"] = anomaly_summary
REPORTS["05_autonomy_summary"] = autonomy_summary

display(anomaly_summary)
display(autonomy_summary)

                 dataset             anomaly  rows
0            fmmcqa_test  REPEATED_CHARACTER     1
1            fmmcqa_test       REPEATED_WORD     6
2           fmmcqa_train  REPEATED_CHARACTER     1
3           fmmcqa_train       REPEATED_WORD    31
4      fmmcqa_validation       REPEATED_WORD     2
5         mqal_mcqm_test    EXCESSIVE_SPACES    43
6         mqal_mcqm_test  REPEATED_CHARACTER    37
7         mqal_mcqm_test       REPEATED_WORD    41
8        mqal_mcqm_train    EXCESSIVE_SPACES    57
9        mqal_mcqm_train  REPEATED_CHARACTER    47
10       mqal_mcqm_train       REPEATED_WORD    51
11  mqal_mcqm_validation    EXCESSIVE_SPACES    12
12  mqal_mcqm_validation  REPEATED_CHARACTER    10
13  mqal_mcqm_validation       REPEATED_WORD    23
14        mqal_mcqu_test    EXCESSIVE_SPACES   465
15        mqal_mcqu_test  REPEATED_CHARACTER    54
16        mqal_mcqu_test       REPEATED_WORD    70
17       mqal_mcqu_train    EXCESSIVE_SPACES   760
18       mqal_mcqu_train  REPEATED_CHARACTER   103
19       mqal_mcqu_train       REPEATED_WORD   104
20  mqal_mcqu_validation    EXCESSIVE_SPACES   180
21  mqal_mcqu_validation  REPEATED_CHARACTER    23
22  mqal_mcqu_validation       REPEATED_WORD    32
23         mqal_oeq_test    EXCESSIVE_SPACES   143
24         mqal_oeq_test  REPEATED_CHARACTER    92
25         mqal_oeq_test       REPEATED_WORD   165
26                 mquad    EXCESSIVE_SPACES  4722
27                 mquad  REPEATED_CHARACTER  3108
28                 mquad       REPEATED_WORD   359
29             umed_test    EXCESSIVE_SPACES    53
30             umed_test  REPEATED_CHARACTER    11
31             umed_test       REPEATED_WORD    11
32            umed_train    EXCESSIVE_SPACES  9543
33            umed_train  REPEATED_CHARACTER  1338
34            umed_train       REPEATED_WORD  1551
35       umed_validation    EXCESSIVE_SPACES   171
36       umed_validation  REPEATED_CHARACTER    28
37       umed_validation       REPEATED_WORD    27

                 dataset            autonomy_status  rows  rate_pct
0         mqal_mcqm_test   AUTONOMOUS_OR_UNDETECTED  3245     95.89
1         mqal_mcqm_test  DEPENDENT_WITHOUT_CONTEXT     2      0.06
2         mqal_mcqm_test     DEPENDENT_WITH_CONTEXT   137      4.05
3        mqal_mcqm_train   AUTONOMOUS_OR_UNDETECTED  5560     96.41
4        mqal_mcqm_train  DEPENDENT_WITHOUT_CONTEXT     3      0.05
5        mqal_mcqm_train     DEPENDENT_WITH_CONTEXT   204      3.54
6   mqal_mcqm_validation   AUTONOMOUS_OR_UNDETECTED  1428     97.41
7   mqal_mcqm_validation  DEPENDENT_WITHOUT_CONTEXT     2      0.14
8   mqal_mcqm_validation     DEPENDENT_WITH_CONTEXT    36      2.46
9         mqal_mcqu_test   AUTONOMOUS_OR_UNDETECTED  4159     95.76
10        mqal_mcqu_test  DEPENDENT_WITHOUT_CONTEXT     9      0.21
11        mqal_mcqu_test     DEPENDENT_WITH_CONTEXT   175      4.03
12       mqal_mcqu_train   AUTONOMOUS_OR_UNDETECTED  9733     96.24
13       mqal_mcqu_train  DEPENDENT_WITHOUT_CONTEXT    12      0.12
14       mqal_mcqu_train     DEPENDENT_WITH_CONTEXT   368      3.64
15  mqal_mcqu_validation   AUTONOMOUS_OR_UNDETECTED  2455     95.86
16  mqal_mcqu_validation  DEPENDENT_WITHOUT_CONTEXT     3      0.12
17  mqal_mcqu_validation     DEPENDENT_WITH_CONTEXT   103      4.02
18         mqal_oeq_test   AUTONOMOUS_OR_UNDETECTED  4649     93.56
19         mqal_oeq_test     DEPENDENT_WITH_CONTEXT   320      6.44

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit linguistique confirme une <strong>forte cohérence entre la langue attendue et la langue détectée</strong>. Les corpus francophones sont reconnus en français dans plus de 99 % des échantillons, tandis que les corpus anglophones sont majoritairement détectés en anglais. Les quelques détections divergentes restent marginales et peuvent correspondre à des textes courts, à du vocabulaire médical ou à des limites du détecteur automatique plutôt qu’à de véritables changements de langue.
  </p>

  <p>
    <strong>Longueur des textes :</strong> les profils diffèrent nettement selon les sources. <strong>FrenchMedMCQA</strong> est court et homogène, tandis que <strong>MediQAl MCQM/MCQU</strong> reste globalement compact mais devient plus long lorsqu’un cas clinique est présent. <strong>MediQAl OEQ</strong> contient des questions et réponses plus développées. <strong>MedQuad-KV</strong> présente une forte variabilité liée principalement à la longueur des réponses. Enfin, <strong>UltraMedical-Preference</strong> contient les séquences les plus longues du corpus global en raison de la présence simultanée du prompt et des réponses <code>chosen</code> et <code>rejected</code>.
  </p>

  <p>
    <strong>Longueur en tokens :</strong> FrenchMedMCQA reste entièrement sous 512 tokens. MediQAl MCQM/MCQU dépasse rarement ce seuil, avec environ <strong>2 %</strong> des exemples concernés et aucun exemple au-dessus de 1 024 tokens. MediQAl OEQ est plus long avec <strong>21,65 %</strong> des exemples au-dessus de 512 tokens, mais seulement <strong>0,72 %</strong> au-dessus de 1 024. MedQuad-KV présente davantage de valeurs extrêmes avec <strong>11,80 %</strong> des exemples au-dessus de 512 tokens, <strong>2,63 %</strong> au-dessus de 1 024 et <strong>0,69 %</strong> au-dessus de 2 048.
  </p>

  <p>
    <strong>UltraMedical-Preference</strong> devra être traité séparément pour le DPO : environ <strong>88 %</strong> des exemples dépassent 512 tokens et près de <strong>39 %</strong> du train dépassent 1 024 tokens. En revanche, seuls <strong>0,53 %</strong> du train dépassent 2 048 tokens. Le choix de la longueur maximale d’entraînement aura donc un impact important sur la quantité de données utilisables et sur les besoins en mémoire.
  </p>

  <p>
    <strong>Anomalies textuelles :</strong> les principales anomalies détectées concernent les espaces excessifs ainsi que certaines répétitions de caractères ou de mots. Elles sont particulièrement visibles dans <strong>MedQuad-KV</strong>, <strong>UltraMedical-Preference</strong> et certains sous-ensembles de MediQAl. Ces signaux ne doivent toutefois pas être interprétés automatiquement comme des erreurs : certaines répétitions peuvent être légitimes dans un texte médical et nécessitent donc un contrôle ciblé.
  </p>

  <p>
    <strong>Autonomie des questions MediQAl :</strong> la très grande majorité des exemples sont classés
    <code>AUTONOMOUS_OR_UNDETECTED</code>, avec environ <strong>94 % à 97 %</strong> selon les sous-ensembles.
    Une petite proportion est explicitement dépendante d’un contexte clinique disponible, généralement entre
    <strong>2,46 % et 6,44 %</strong>. Les cas réellement problématiques, classés
    <code>DEPENDENT_WITHOUT_CONTEXT</code>, sont très rares : ils représentent au maximum
    <strong>0,21 %</strong> des exemples dans les sous-ensembles concernés. Cela confirme que l’absence de
    <code>clinical_case</code> observée précédemment ne constitue pas en elle-même un motif de suppression.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>conserver la langue documentée comme référence et examiner uniquement les détections linguistiques divergentes avant toute exclusion ;</li>
    <li>normaliser les espaces superflus et les anomalies typographiques simples sans modifier le contenu médical ;</li>
    <li>ne pas supprimer automatiquement les répétitions de mots ou de caractères, mais contrôler les exemples signalés afin de distinguer bruit de format et contenu légitime ;</li>
    <li>ne pas supprimer un exemple MediQAl uniquement parce que <code>clinical_case</code> est absent ;</li>
    <li>conserver les exemples <code>DEPENDENT_WITH_CONTEXT</code> en associant obligatoirement leur contexte clinique à la question lors de la construction du SFT ;</li>
    <li>examiner en priorité les rares exemples <code>DEPENDENT_WITHOUT_CONTEXT</code> et les exclure s’ils ne peuvent pas être rendus autonomes sans inventer d’information ;</li>
    <li>conserver les exemples longs lorsqu’ils restent compatibles avec la fenêtre de contexte du modèle choisi et examiner particulièrement les valeurs extrêmes de MedQuad-KV ;</li>
    <li>définir une longueur maximale adaptée au DPO pour UltraMedical-Preference afin de limiter les troncatures de <code>chosen</code> et <code>rejected</code> ;</li>
    <li>effectuer les éventuelles troncatures dans le pipeline d’entraînement plutôt que dans les données brutes afin de préserver l’intégrité et la traçabilité des corpus.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">6. Répétitions, quasi-doublons et contradictions</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Distinguer les répétitions légitimes des exemples réellement équivalents et des conflits de cible.
</div>


<p>L’audit original détecte notamment 2 510 paires de quasi-doublons candidates dans MedQuAD, 640 dans UltraMedical train et 355 dans MediQAl MCQU train. Il identifie également 129 groupes QCM potentiellement contradictoires dans MediQAl, représentant 280 observations.</p>

<p><strong>Règle centrale :</strong> une réponse identique n’est jamais un doublon à elle seule. Des cas cliniques différents peuvent légitimement conduire à la même réponse.</p>

In [12]:
# Empreintes normalisées

# Normalise entrées et sorties puis calcule des empreintes stables.
# Elles permettent de détecter les répétitions sans dépendre de la forme du texte.
audit_records["input_norm"] = audit_records["input_text"].map(
    lambda x: normalize_text(x, remove_punctuation=True)
)

audit_records["target_norm"] = audit_records.apply(
    lambda row: normalize_text(
        row["target_text"]
        or "\n".join([row["chosen_text"], row["rejected_text"]]),
        remove_punctuation=True
    ),
    axis=1
)

audit_records["input_hash"] = audit_records["input_norm"].map(stable_hash)
audit_records["target_hash"] = audit_records["target_norm"].map(stable_hash)

audit_records["example_hash"] = audit_records.apply(
    lambda row: stable_hash(row["input_norm"], row["target_norm"]),
    axis=1
)

audit_records["group_hash"] = audit_records["group_text"].map(
    lambda x: stable_hash(normalize_text(x, remove_punctuation=True))
)


# Groupes répétés

# Compte les empreintes apparaissant plusieurs fois dans chaque dataset.
# Distingue les entrées répétées des exemples complets réellement répétés.
def repeated_group_summary(
    df: pd.DataFrame,
    key: str,
    label: str
) -> pd.DataFrame:
    """Résume les groupes répétés."""
    counts = (
        df.groupby(["dataset", key])
        .size()
        .rename("group_size")
        .reset_index()
    )

    repeated = counts[counts["group_size"].gt(1)]

    return (
        repeated
        .groupby("dataset")
        .agg(
            repeated_groups=(key, "size"),
            repeated_rows=("group_size", "sum")
        )
        .reset_index()
        .assign(repetition_type=label)
    )


# Détection

# Recherche les répétitions d'exemples complets puis celles des seules entrées.
# Les résultats restent descriptifs et ne suppriment aucun enregistrement.
complete_repetitions = repeated_group_summary(
    audit_records,
    "example_hash",
    "NORMALIZED_COMPLETE"
)

input_repetitions = repeated_group_summary(
    audit_records,
    "input_hash",
    "NORMALIZED_INPUT"
)


# Rapports

# Archive les deux niveaux de répétition dans le registre commun des audits.
# Ils serviront ensuite au contrôle des doublons et des fuites entre splits.
REPORTS["06_normalized_complete_repetitions"] = complete_repetitions
REPORTS["06_normalized_input_repetitions"] = input_repetitions

display(complete_repetitions)
display(input_repetitions)

                 dataset  repeated_groups  repeated_rows      repetition_type
0           fmmcqa_train                5             10  NORMALIZED_COMPLETE
1         mqal_mcqm_test               39             79  NORMALIZED_COMPLETE
2        mqal_mcqm_train               69            141  NORMALIZED_COMPLETE
3   mqal_mcqm_validation                2              4  NORMALIZED_COMPLETE
4         mqal_mcqu_test               59            121  NORMALIZED_COMPLETE
5        mqal_mcqu_train              209            426  NORMALIZED_COMPLETE
6   mqal_mcqu_validation               12             24  NORMALIZED_COMPLETE
7                  mquad               32             80  NORMALIZED_COMPLETE
8              umed_test                1              2  NORMALIZED_COMPLETE
9             umed_train            12438          24876  NORMALIZED_COMPLETE
10       umed_validation                4              8  NORMALIZED_COMPLETE

                 dataset  repeated_groups  repeated_rows   repetition_type
0           fmmcqa_train                5             10  NORMALIZED_INPUT
1         mqal_mcqm_test               45             91  NORMALIZED_INPUT
2        mqal_mcqm_train               91            186  NORMALIZED_INPUT
3   mqal_mcqm_validation                2              4  NORMALIZED_INPUT
4         mqal_mcqu_test               61            125  NORMALIZED_INPUT
5        mqal_mcqu_train              210            428  NORMALIZED_INPUT
6   mqal_mcqu_validation               12             24  NORMALIZED_INPUT
7          mqal_oeq_test               25             53  NORMALIZED_INPUT
8                  mquad             1453           3562  NORMALIZED_INPUT
9              umed_test                1              2  NORMALIZED_INPUT
10            umed_train            27091          60195  NORMALIZED_INPUT
11       umed_validation               16             33  NORMALIZED_INPUT

In [13]:
# Doublons proches

# Recherche les entrées similaires avec RapidFuzz dans des groupes de longueur comparable.
# Les doublons exacts et les textes trop différents en longueur sont exclus.
def find_near_duplicates(
    df: pd.DataFrame,
    threshold: int = NEAR_DUPLICATE_THRESHOLD,
    window: int = NEAR_DUPLICATE_WINDOW
) -> pd.DataFrame:
    """Détecte les doublons proches."""
    columns = ["dataset", "first_id", "second_id", "score"]

    if not RAPIDFUZZ_AVAILABLE or not RUN_NEAR_DUPLICATES:
        return pd.DataFrame(columns=columns)

    work = df[df["input_norm"].str.len().gt(0)].copy()
    work["length_bucket"] = work["input_norm"].str.len() // 100
    candidates = []

    for (dataset, _), group in work.groupby(
        ["dataset", "length_bucket"],
        sort=False
    ):
        group = group.sort_values("input_norm", kind="stable")
        indices = list(group.index)

        for pos, first in enumerate(indices):
            text_a = group.at[first, "input_norm"]

            for second in indices[pos + 1:pos + 1 + window]:
                text_b = group.at[second, "input_norm"]

                if text_a == text_b:
                    continue

                length_ratio = min(len(text_a), len(text_b)) / max(
                    len(text_a),
                    len(text_b)
                )

                if length_ratio < 0.80:
                    continue

                score = max(
                    fuzz.ratio(text_a, text_b),
                    fuzz.token_set_ratio(text_a, text_b)
                )

                if score >= threshold:
                    candidates.append({
                        "dataset": dataset,
                        "first_id": group.at[first, "id"],
                        "second_id": group.at[second, "id"],
                        "score": round(float(score), 2)
                    })

    return pd.DataFrame(candidates, columns=columns)


# Synthèse

# Exécute la détection puis compte les paires candidates par dataset.
# Ces similarités restent des signaux d'audit et non des suppressions automatiques.
near_duplicates = find_near_duplicates(audit_records)

near_duplicate_summary = (
    near_duplicates
    .groupby("dataset")
    .size()
    .rename("candidate_pairs")
    .reset_index()
    if not near_duplicates.empty
    else pd.DataFrame(columns=["dataset", "candidate_pairs"])
)


# Rapports

# Conserve le détail des paires et leur synthèse dans le registre des audits.
# Le détail permet une revue ultérieure des similarités détectées.
REPORTS["06_near_duplicates_details"] = near_duplicates
REPORTS["06_near_duplicates_summary"] = near_duplicate_summary

display(near_duplicate_summary)

                 dataset  candidate_pairs
0            fmmcqa_test                2
1           fmmcqa_train               16
2         mqal_mcqm_test              157
3        mqal_mcqm_train              336
4   mqal_mcqm_validation               22
5         mqal_mcqu_test              181
6        mqal_mcqu_train              628
7   mqal_mcqu_validation               40
8          mqal_oeq_test             2738
9                  mquad             2403
10            umed_train             3279
11       umed_validation                1

In [14]:
# Contradictions QCM

# Repère une même question associée à plusieurs réponses correctes normalisées.
# Ces cas signalent une incohérence potentielle nécessitant une vérification.
qcm_conflicts = (
    audit_records[
        audit_records["family"].isin({"qcm_fmm", "qcm_mcqm", "qcm_mcqu"})
    ]
    .groupby(["dataset", "input_hash"])
    .agg(
        rows=("id", "size"),
        distinct_targets=("target_hash", "nunique"),
        ids=("id", list)
    )
    .reset_index()
)

qcm_conflicts = qcm_conflicts[
    qcm_conflicts["distinct_targets"].gt(1)
]


# Réponses multiples MedQuAD

# Repère une même question MedQuAD associée à plusieurs réponses normalisées.
# Une multiplicité est signalée pour analyse sans être considérée automatiquement comme erreur.
mquad_multiple_answers = (
    audit_records[
        audit_records["source"].eq("MedQuad-KV")
    ]
    .groupby("input_hash")
    .agg(
        rows=("id", "size"),
        distinct_targets=("target_hash", "nunique"),
        ids=("id", list)
    )
    .reset_index()
)

mquad_multiple_answers = mquad_multiple_answers[
    mquad_multiple_answers["distinct_targets"].gt(1)
]


# Rapports

# Archive les contradictions QCM et les réponses multiples MedQuAD séparément.
# Un aperçu limité à 20 lignes facilite leur inspection dans le notebook.
REPORTS["06_qcm_contradictions"] = qcm_conflicts
REPORTS["06_mquad_multiple_answers"] = mquad_multiple_answers

display(qcm_conflicts.head(20))
display(mquad_multiple_answers.head(20))

,dataset,input_hash,rows,distinct_targets,ids
3235,mqal_mcqm_test,0c52674887908bb02453fabdeaac880b4f3e1a1b516f71333d8d838c47030aa5,2,2,"[832a9243a89986cdae8a544f, ea8d9a10652514b04d8a3375]"
4093,mqal_mcqm_test,4c6936a1905a4bdc463d5ca9119cb008983513bc64540b85e0d44a47b8c48c61,2,2,"[845eb7d13bb9003a1bb14587, 872e4fd0053da88c905228b5]"
4300,mqal_mcqm_test,5ce1a439797a27cdfcfef3cb5133056a3c34c2961febf3885975d64bacfe2049,2,2,"[b108f58731e97453e99d22fd, 74fb5219e5f60b815425c93b]"
5379,mqal_mcqm_test,aed278f4993324bf738a6f467342608ab801b9744dab0e8d97f7cabc711756b9,2,2,"[b372331e4324b507298321a4, ef9644b2face2088e7c7509c]"
5392,mqal_mcqm_test,afdd63554eb1e4edb2e4c8dbf419dde16172690eb270678e23569c86c268eafb,2,2,"[e86f68b4424d9de3cda2137c, 19325f3d49f91e3d9cd76ee6]"
6257,mqal_mcqm_test,f196289615f52c1f97bf0f0a102fa974920279888fa3bc42b50c41a1c0a560c4,2,2,"[c241cef747b9fcb523b712c7, f4b26c55753f5d7fec66c198]"
6657,mqal_mcqm_train,09ed41a7a863510c30baa5331370eabfa58dc0168ff3e024e72e45f318d9d10f,2,2,"[8074c74f7ddfff0127040d6b, 384e1eb33e7726f5bce6eeb1]"
6918,mqal_mcqm_train,15616ca711d1442b6a05757bd8875d43be5895c3a3fb0d410a135ca96a13e314,2,2,"[fa13995338b30c1a55e93b82, c7ff026c7eaefe60252a8af8]"
7211,mqal_mcqm_train,2330448f8b5cec5c93c02b710804770d10022b67db4180622e625e57cda88a1e,2,2,"[1c6e9ad6995fe5fb43446a1e, c63a1c206ea079789c4b65a9]"
7387,mqal_mcqm_train,2ae011d3e39c43c33965ef073b1f087bea94e4bcdbbcfdddc64f63c7620f6ca5,2,2,"[d7d4ad420bd9cbb69d7830aa, 7c1680901097a095dd983159]"
7489,mqal_mcqm_train,2f353d91ee7b5af46ab62b4874a3708fca7bb884da7f02fa448c7ad2c7e051d9,2,2,"[fecf5b4de2e376e08f4ccfa7, 8b5756a84d4e3a705e1aa7af]"
7880,mqal_mcqm_train,40974fbbb1e76b1858bda6f1829adfc2d5d69828c546f8e65ff6b329a9c250a1,2,2,"[bee6b62e8d9cc80b9fd9365d, 854511154ecb756e75c870c6]"
8025,mqal_mcqm_train,46f9b513244131a7e646aac8f44079d5b5eb8817fac508e06f9a749820866b76,4,2,"[1b02578f22705b84edc4a1b3, 3a5b89e7bd878afdccd3bf3b, ca69a73be8171358bdfbd790, b5dced19774aeab333b1850e]"
8325,mqal_mcqm_train,55a5386ccbc175cc899c8dd7cd39e0ed7f28a68ddf7bc51a0cd2112ad994ca44,2,2,"[59cf17a3b2a5983a37023013, 88e139c232d84c78470be387]"
8362,mqal_mcqm_train,57419fa269d0219545d3f7e65e4a32360e52fbf67f6aefe4b6934a8ca67cf127,2,2,"[d706e7c62701e543a73ec077, 1489efe870762c42ba9eb023]"
8497,mqal_mcqm_train,5d728d4dda7cb63de7c3f86868507a6b4ce20ce91d8edc2d1a8d0bd04dc64fbc,2,2,"[04bc5b7de81d21c086188aad, 9163fefd48ee52fb22a6613a]"
8952,mqal_mcqm_train,722ac8cd3411bcf9444aa30416534f9d932c6fc1d5b5ba0885ab688896ddeaff,2,2,"[30805163683386644222f4eb, 7a1556eba44b24070f8ffd47]"
9190,mqal_mcqm_train,7b59b9680adb76405d255735f310738da2e263d0b9e54aa526d79501bc4cfbc4,2,2,"[ad51d79b5bf444ef18859182, 846279936a299333630299cf]"
9968,mqal_mcqm_train,9f4970cb99c1140663fa26550451adbd1916861427c3ac1c32edc80751cb1551,2,2,"[318b654faac44a6ae61c8c65, af547b2266833b4531eee5dd]"
10185,mqal_mcqm_train,aa22bd042eba89e8ccf8b5fad9914dd99527fedb6923157b9ba5830d4167d07f,2,2,"[b37d96f1b90c064d3cdb266b, 66c07e59c0c77f474d3b167f]"

,input_hash,rows,distinct_targets,ids
1,000d90790651213e06ab72de788d2f0c5de0b2d8b5d10228007d7b1317c6747c,4,4,"[0bd3f708a5cc8d3b3b00c826, f8ef6d406dd51ed7fc04ed0c, 454f64b2524e5b9ad87923fb, f1b40679a64ac80b95ab41c1]"
2,001283bd376235e8d185acddb29f2f2a6d1ebbb0421e713f85be984d738bc3ac,2,2,"[c8b77e76482bae73cacbf05d, aa096250297a5b7b2a69c8e5]"
7,00238cc53dd247546cce7524b80efff4db5f65b540552814434fb381b4001020,3,3,"[afc7eb5218410ec734703a06, 36db47a4cd90a8a5f0f5aab6, b3d720443fd92fb76c2b5341]"
8,00306e48de5870c5e622adc4ba90cb8014541e336f4c6496f41bc9bb37c8f867,2,2,"[d543726c57a1c5e540ef6e26, c1fd59aeb04d5ca651ac658f]"
28,007c2f5f96cbdcf212ff998f6de3d7bfd4f542220aae644db1593ed6f2053229,2,2,"[de5b50439787226a7b105b94, 1956c2e71cf3506fee3a95f5]"
47,00e826d4a575fe78321c5a9118bda145f20d66622b2ec5b7c5aaabed46ac75e8,2,2,"[bee70b4306cdf92f2fe4cfc9, c78f3fb63780d6a283ecd2d9]"
59,0132b4bc8994cacb485b2c56ec5bf9cd2da0b7541d4437398b20cf0b1fb19446,2,2,"[af3675ace7608faa48ef8be0, 71002ac62e4855d527f49d3a]"
67,015500ba9a42547cbadc76888bdba5a55b7469fef6f2c0dfb8ee2995b8d53f72,2,2,"[1278a3799345cb1b014574c2, c67ff433132cadb466bca70b]"
83,01978c19166c3f2f09557a308c5169a03cbcd6086ffa1a196148a8a0db3c962b,2,2,"[64e36d1e45dbbaae5f9b3bdc, 6f44357694633c4bae9fd2bb]"
122,02582a6bddaa19e2d946ae89aafb232ae541654a85cd1fb270257b669586b26b,2,2,"[314078a07d6ea7b2e9be7f66, 559f9b965e35da21835eb14b]"
129,0272386f112ad84255ce201b46380ceef67f73257e5deaa5db27a35e5fc211dc,2,2,"[828ae32c951871a12898b223, 7550ac7dbf3e476b806b3a63]"
130,02829e2cf3dde21b8d3022de1b86b24436fd973cf83549b1fa6874e4b26bbb88,2,2,"[a8a311938abc13ab34e928f9, 4295f84d4474e59a6c6befd6]"
142,02afc752b59e2d1663b5e584b91eb3f5a3a72a8b328509ad4f8130992f8d23fe,2,2,"[856b5124f19c0993116e803a, 768897a24e813ba3b85b9885]"
149,02c71b4a1a1ec79f13f6908db40a3af4f338d7733b568a3988df8758436e8146,2,2,"[557e4fd9d51f81d13375cfb0, 0a04140ba3ff25d009520b3b]"
162,0308696af2b6c9e7eb6467d278e982ab80181c9a273a3710c7b2ea7034643580,2,2,"[2b80e9fc9049c1345684f20b, 6f6e8e9e05c5a3721e933db5]"
166,032059416513f482ae7358fc2fbe7c0a699fe9f578f65b168681a51f92678ea9,2,2,"[f9c08507db8231767fb99b62, 531421f9bf06671b4311da8a]"
168,03270152cc37d040fcaf2af306b449e0cf77a646df321e49590c464e80a9cc0a,3,3,"[a45c355536d3b0f7dd2f865c, df7d5861979ef2135d45e032, d80ef86d878def3f46adb540]"
177,034cfbccc35db1b609e44312c3425210c4f95f8dfab4c5d2c681e4d2f2ab4b60,2,2,"[bf57bf5fe9df87cacf64fe13, 436b96d860b8eebc8d0cd3a8]"
197,03ae96277acf68250f50c46311611a8c364d5406c5d74141c34cae85eaa50625,2,2,"[593b95842acc2fc4112d8a4e, 20b79ae33d341c00988c46b7]"
208,03d917af670bff0ad45987232e4edb15fc5c746923385d935c2064e59c251c8d,2,2,"[580d1ccd8bd8c018eb22f990, 7a9e854759da8f9630327434]"

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit des répétitions met en évidence des niveaux très différents selon les corpus. <strong>FrenchMedMCQA</strong> contient très peu de doublons complets, avec seulement <strong>5 groupes pour 10 lignes</strong> dans le train. <strong>MediQAl</strong> présente davantage de répétitions, surtout dans les sous-ensembles MCQU et MCQM, mais elles restent limitées au regard du volume total. <strong>MedQuad-KV</strong> contient peu de doublons complets mais beaucoup plus de questions répétées après normalisation, tandis qu’<strong>UltraMedical-Preference</strong> concentre de loin le plus grand volume de répétitions.
  </p>

  <p>
    <strong>Doublons exacts :</strong> les répétitions complètes peuvent généralement être considérées comme redondantes lorsqu’elles reproduisent exactement le même exemple. Elles représentent notamment <strong>426 lignes dans MediQAl MCQU train</strong>, <strong>141 lignes dans MediQAl MCQM train</strong> et surtout <strong>24 876 lignes dans UltraMedical-Preference train</strong>. Ces doublons constituent une cible directe de déduplication, sous réserve de conserver un exemplaire et les informations nécessaires à la traçabilité.
  </p>

  <p>
    <strong>Répétitions après normalisation :</strong> elles sont plus nombreuses que les doublons stricts. <strong>MedQuad-KV</strong> comporte <strong>1 453 groupes de questions répétées pour 3 562 lignes</strong>, ce qui indique qu’une même question peut apparaître plusieurs fois, parfois avec des réponses différentes. Dans <strong>UltraMedical-Preference train</strong>, <strong>27 091 groupes</strong> concernent <strong>60 195 lignes</strong>. Ces répétitions ne doivent pas être supprimées automatiquement sur la seule base du prompt ou de la question, car elles peuvent correspondre à plusieurs réponses ou préférences réellement distinctes.
  </p>

  <p>
    <strong>Quasi-doublons :</strong> plusieurs milliers de paires candidates sont détectées, notamment dans <strong>MediQAl OEQ</strong> avec <strong>2 738 paires</strong>, <strong>MedQuad-KV</strong> avec <strong>2 403</strong> et <strong>UltraMedical-Preference train</strong> avec <strong>3 279</strong>. Ces résultats constituent des candidats à examiner et non des doublons confirmés. Une forte similarité peut correspondre à une reformulation légitime, à deux cas cliniques proches ou à des questions appartenant au même thème médical.
  </p>

  <p>
    <strong>Contradictions dans les QCM :</strong> l’audit identifie dans <strong>MediQAl MCQM</strong> plusieurs questions normalisées identiques associées à des réponses cibles différentes. La majorité des groupes affichés contiennent deux lignes et deux réponses distinctes, avec au moins un cas comportant <strong>4 lignes pour 2 réponses différentes</strong>. Ces exemples ne doivent pas être dédupliqués aveuglément : ils peuvent correspondre à une erreur d’annotation, à une différence de contexte perdue lors de la normalisation ou à une véritable incohérence médicale.
  </p>

  <p>
    <strong>MedQuad-KV</strong> présente également un nombre important de questions identiques associées à plusieurs réponses distinctes, parfois jusqu’à <strong>4 réponses différentes pour une même question normalisée</strong> dans les exemples observés. Dans un corpus de questions-réponses ouvertes, cette situation n’est pas nécessairement contradictoire : plusieurs réponses peuvent être complémentaires ou formuler différemment une même information. Une analyse du contenu des réponses est donc nécessaire avant toute fusion ou suppression.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>supprimer les <strong>doublons complets strictement identiques</strong> en conservant un exemplaire et les informations de traçabilité ;</li>
    <li>ne pas supprimer automatiquement les répétitions détectées uniquement sur l’<code>input_text</code> ou le prompt normalisé ;</li>
    <li>pour <strong>UltraMedical-Preference</strong>, dédupliquer sur le triplet complet <code>prompt / chosen / rejected</code> plutôt que sur le seul prompt ;</li>
    <li>examiner les quasi-doublons selon leur similarité réelle avant toute suppression, notamment pour MediQAl OEQ, MedQuad-KV et UltraMedical-Preference ;</li>
    <li>placer en <strong>revue prioritaire</strong> les questions MediQAl identiques associées à plusieurs réponses cibles afin de distinguer erreur d’annotation, perte de contexte et cas légitime ;</li>
    <li>pour MedQuad-KV, conserver les réponses multiples lorsqu’elles sont compatibles ou complémentaires et exclure uniquement les contradictions réelles ;</li>
    <li>effectuer la déduplication avant la constitution définitive des splits afin d’éviter qu’un même exemple, ou une variante très proche, soit présent à la fois dans l’entraînement et l’évaluation ;</li>
    <li>conserver les rapports de doublons, quasi-doublons et contradictions afin que chaque suppression ou conservation soit traçable dans le notebook de nettoyage.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">7. Audit de diversité</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Mesurer les déséquilibres de sources, spécialités, formats, contextes et tâches avant la sélection future.
</div>


<p>UltraMedical représente 68,31 % du volume brut, MediQAl 19,82 %, MedQuAD 9,98 % et FrenchMedMCQA 1,89 %. Ces poids ne doivent pas être reproduits mécaniquement. Le SFT devra combiner QCM uniques, QCM multiples, questions ouvertes et raisonnement contextualisé.</p>

In [15]:
# Diversité des sources et tâches

# Mesure la représentation de chaque source et des différents types de tâches.
# Les proportions permettent de repérer une éventuelle domination d'un corpus.
source_diversity = (
    audit_records.groupby("source")
    .size()
    .rename("rows")
    .reset_index()
)

source_diversity["rate_pct"] = (
    source_diversity["rows"] / len(audit_records) * 100
).round(2)

task_diversity = (
    audit_records
    .groupby(["source", "task_type"])
    .size()
    .rename("rows")
    .reset_index()
)


# Diversité des contextes

# Mesure la présence ou l'absence d'un contexte clinique selon le dataset.
# Ce contrôle permet d'évaluer la variété des formats d'entrée.
context_diversity = (
    audit_records
    .groupby(["dataset", "has_context"])
    .size()
    .rename("rows")
    .reset_index()
)


# Diversité médicale

# Mesure la couverture des spécialités et des différents types de questions.
# Les valeurs manquantes de question_type restent visibles dans le rapport.
specialty_diversity = (
    audit_records[audit_records["medical_subject"].str.len().gt(0)]
    .groupby(["source", "medical_subject"])
    .size()
    .rename("rows")
    .reset_index()
    .sort_values(["source", "rows"], ascending=[True, False])
)

question_type_diversity = (
    audit_records
    .assign(
        question_type_clean=audit_records["question_type"]
        .replace("", "<MISSING>")
    )
    .groupby(["dataset", "question_type_clean"])
    .size()
    .rename("rows")
    .reset_index()
)


# Rapports

# Archive chaque dimension de diversité séparément dans le registre des audits.
# L'affichage des spécialités est limité aux 15 principales par source.
REPORTS["07_source_diversity"] = source_diversity
REPORTS["07_task_diversity"] = task_diversity
REPORTS["07_context_diversity"] = context_diversity
REPORTS["07_specialty_diversity"] = specialty_diversity
REPORTS["07_question_type_diversity"] = question_type_diversity

display(source_diversity)
display(task_diversity)
display(context_diversity)
display(specialty_diversity.groupby("source").head(15))

                    source    rows  rate_pct
0            FrenchMedMCQA    3105      1.89
1               MedQuad-KV   16407      9.98
2                  MediQAl   32603     19.82
3  UltraMedical-Preference  112362     68.31

                    source task_type    rows
0            FrenchMedMCQA       QCM    3105
1               MedQuad-KV   OPEN_QA   16407
2                  MediQAl      MCQM   10617
3                  MediQAl      MCQU   17017
4                  MediQAl   OPEN_QA    4969
5  UltraMedical-Preference       DPO  112362

                 dataset  has_context    rows
0            fmmcqa_test        False     622
1           fmmcqa_train        False    2171
2      fmmcqa_validation        False     312
3         mqal_mcqm_test        False    2042
4         mqal_mcqm_test         True    1342
5        mqal_mcqm_train        False    3582
6        mqal_mcqm_train         True    2185
7   mqal_mcqm_validation        False     919
8   mqal_mcqm_validation         True     547
9         mqal_mcqu_test        False    2347
10        mqal_mcqu_test         True    1996
11       mqal_mcqu_train        False    6178
12       mqal_mcqu_train         True    3935
13  mqal_mcqu_validation        False    1562
14  mqal_mcqu_validation         True     999
15         mqal_oeq_test        False    1015
16         mqal_oeq_test         True    3954
17                 mquad        False   16407
18             umed_test        False     777
19            umed_train        False  109353
20       umed_validation        False    2232

           source               medical_subject  rows
0   FrenchMedMCQA                     pharmacie  3105
4         MediQAl                    Cardiology  2141
15        MediQAl       Hepato-Gastroenterology  1899
13        MediQAl     Gynecology and Obstetrics  1760
37        MediQAl                   Pulmonology  1739
14        MediQAl                    Hematology  1666
22        MediQAl                Nephro-Urology  1666
33        MediQAl                      Pharmacy  1544
9         MediQAl  Endocrinology and Metabolism  1477
23        MediQAl                     Neurology  1327
35        MediQAl                    Psychiatry  1325
31        MediQAl                    Pediatrics  1305
40        MediQAl                  Rheumatology  1285
19        MediQAl           Infectious Diseases  1274
30        MediQAl          Pediatric Cardiology  1225
27        MediQAl     Otorhinolaryngology (ENT)  1083

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit de diversité montre un corpus globalement riche, mais <strong>fortement déséquilibré selon les sources</strong>. <strong>UltraMedical-Preference</strong> représente à lui seul <strong>68,31 %</strong> des lignes auditées, contre <strong>19,82 %</strong> pour MediQAl, <strong>9,98 %</strong> pour MedQuad-KV et seulement <strong>1,89 %</strong> pour FrenchMedMCQA. Cette domination est cohérente avec son rôle spécifique pour le DPO, mais elle impose de séparer clairement les analyses SFT et DPO afin que le volume brut ne soit pas interprété comme un équilibre réel entre les usages.
  </p>

  <p>
    <strong>Diversité des tâches :</strong> les corpus couvrent plusieurs formats complémentaires. FrenchMedMCQA apporte <strong>3 105 QCM</strong>, MediQAl combine <strong>10 617 MCQM</strong>, <strong>17 017 MCQU</strong> et <strong>4 969 questions ouvertes</strong>, MedQuad-KV fournit <strong>16 407 questions-réponses ouvertes</strong> et UltraMedical-Preference contient <strong>112 362 exemples DPO</strong>. Cette complémentarité est utile pour construire des datasets spécialisés, mais les proportions finales devront être définies volontairement plutôt que reproduire mécaniquement les volumes disponibles.
  </p>

  <p>
    <strong>Présence du contexte clinique :</strong> FrenchMedMCQA, MedQuad-KV et UltraMedical-Preference ne disposent pas de contexte clinique séparé dans leur schéma canonique. MediQAl est le seul corpus à fournir régulièrement un <code>clinical_case</code>. Environ <strong>37 à 46 %</strong> des exemples MCQM/MCQU possèdent un contexte selon les splits, tandis que MediQAl OEQ en contient beaucoup plus fréquemment avec <strong>3 954 exemples sur 4 969</strong>, soit près de <strong>80 %</strong>. Cette diversité permet de conserver à la fois des questions autonomes et des situations cliniques contextualisées.
  </p>

  <p>
    <strong>Diversité médicale :</strong> MediQAl apporte une couverture relativement large de spécialités, notamment la cardiologie, l’hépato-gastroentérologie, la gynécologie-obstétrique, la pneumologie, l’hématologie, la néphro-urologie, la neurologie, la psychiatrie, la pédiatrie et les maladies infectieuses. FrenchMedMCQA apparaît ici entièrement rattaché à la catégorie <strong>pharmacie</strong>, ce qui indique que ce champ ne doit pas être utilisé seul pour mesurer toute la diversité médicale de ce corpus sans vérifier la signification réelle de sa métadonnée <code>subject_name</code>.
  </p>

  <p>
    Pour le futur dataset SFT de <strong>5 000 exemples</strong>, l’enjeu principal sera donc de sélectionner les données selon leur <strong>qualité, leur pertinence clinique, leur type de tâche et leur diversité</strong>, plutôt que proportionnellement au volume disponible. La constitution du dataset final devra notamment éviter qu’un corpus ou une spécialité domine excessivement les autres.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage et la sélection :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>traiter séparément les volumes <strong>SFT</strong> et <strong>DPO</strong>, UltraMedical-Preference n’ayant pas vocation à participer directement au même échantillonnage que les corpus SFT ;</li>
    <li>construire le SFT à partir d’un échantillonnage contrôlé entre QCM, questions ouvertes et exemples contextualisés plutôt qu’en suivant les proportions brutes des sources ;</li>
    <li>préserver une part suffisante d’exemples avec contexte clinique MediQAl afin de représenter des situations proches du triage médical ;</li>
    <li>conserver également des questions autonomes lorsque leur contenu est complet et médicalement exploitable ;</li>
    <li>contrôler la distribution des spécialités avant la sélection finale afin d’éviter une surreprésentation de quelques domaines médicaux ;</li>
    <li>ne pas utiliser automatiquement <code>subject_name</code> de FrenchMedMCQA comme preuve d’une couverture limitée à la pharmacie sans vérifier sa sémantique dans le dataset source ;</li>
    <li>maintenir les métadonnées de source, tâche, spécialité et présence de contexte dans les données nettoyées afin de permettre un échantillonnage final traçable et reproductible.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">8. Audit médical, sécurité clinique et triage</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Caractériser la pertinence médicale, la proximité avec le triage et les contenus à fort enjeu sans créer de labels cliniques artificiels.
</div>


<p>MediQAl OEQ et UltraMedical contiennent de nombreux signaux proches du triage, mais aucun corpus ne fournit de priorité clinique validée. Les marqueurs aigus, signes vitaux, détresses et catégories sensibles servent uniquement à caractériser et sélectionner les exemples.</p>

In [16]:
# Vocabulaire médical

# Regroupe les termes médicaux généraux FR / EN utilisés pour qualifier le contenu.
# Ce lexique sert de signal documentaire et non de diagnostic clinique.
MEDICAL_TERMS = {
    "symptom", "symptoms", "symptome", "symptomes", "pain", "douleur",
    "fever", "fievre", "dyspnea", "dyspnee", "breath", "respiration",
    "bleeding", "hemorrhage", "hemorragie", "vomiting", "vomissement",
    "nausea", "nausee", "cough", "toux", "fatigue", "weakness",
    "patient", "patiente", "patients", "disease", "maladie", "syndrome",
    "diagnosis", "diagnostic", "treatment", "traitement", "therapy", "therapie",
    "medication", "medicament", "drug", "dose", "dosage", "blood", "sang",
    "heart", "cardiac", "coeur", "cardiaque", "lung", "pulmonary",
    "poumon", "pulmonaire", "renal", "kidney", "rein", "hepatic", "liver",
    "foie", "neurological", "neurologique", "infection", "infectious",
    "infectieux", "cancer", "tumor", "tumeur", "fracture", "trauma",
    "traumatisme", "pregnancy", "grossesse", "surgery", "chirurgie",
    "emergency", "urgence", "clinical", "clinique", "examination", "examen",
    "test", "analyse", "pressure", "tension", "temperature", "pulse", "pouls",
    "oxygen", "oxygene", "saturation"
}


# Marqueurs de triage

# Regroupe les indices cliniques FR / EN pertinents pour l'analyse du triage.
# Les expressions régulières détectent des signaux sans attribuer de priorité.
TRIAGE_MARKERS = {
    "RESPIRATORY_DISTRESS": [
        r"\bdyspn", r"\bdetresse respiratoire\b", r"\bdifficulte respiratoire\b",
        r"\bshortness of breath\b", r"\brespiratory distress\b", r"\bhypoxi",
        r"\bcyan", r"\bsaturation\b", r"\bspo2\b"
    ],
    "CONSCIOUSNESS": [
        r"\bconscience\b", r"\binconscient", r"\bcoma\b", r"\bconfusion\b",
        r"\bsyncope\b", r"\bunconscious\b", r"\bglasgow\b", r"\bgcs\b"
    ],
    "HEMODYNAMIC": [
        r"\bhypotension\b", r"\bhypertension\b", r"\btension arterielle\b",
        r"\bblood pressure\b", r"\btachycard", r"\bbradycard", r"\bpouls\b",
        r"\bpulse\b", r"\bshock\b", r"\bchoc\b"
    ],
    "BLEEDING": [
        r"\bhemorrag", r"\bsaign", r"\bbleeding\b", r"\bhemorrhag",
        r"\bhematem", r"\bmelena\b"
    ],
    "TRAUMA": [
        r"\btrauma", r"\btraumatis", r"\bfracture\b", r"\baccident\b",
        r"\bchute\b", r"\bfall\b", r"\bhead injury\b"
    ],
    "ACUTE_NEUROLOGICAL": [
        r"\bavc\b", r"\bstroke\b", r"\bconvulsion", r"\bseizure",
        r"\bparalys", r"\bdeficit neurolog", r"\bneurological deficit\b"
    ],
    "ACUTE_PAIN": [
        r"\bdouleur\b", r"\bpain\b", r"\bthorac",
        r"\bchest pain\b", r"\babdominal pain\b"
    ],
    "VITAL_SIGNS": [
        r"\btemperature\b", r"\bfievre\b", r"\bfever\b",
        r"\bfrequence cardiaque\b", r"\bheart rate\b",
        r"\bfrequence respiratoire\b", r"\brespiratory rate\b",
        r"\bsaturation\b", r"\bspo2\b"
    ],
    "ACUTE_CONTEXT": [
        r"\burgence", r"\bemergency\b", r"\baigu", r"\bacute\b",
        r"\bsoudain", r"\bsudden\b", r"\bbrutal",
        r"\bdepuis \d+ (minute|minutes|heure|heures|jour|jours)"
    ]
}


# Situations à risque

# Identifie les situations cliniques nécessitant une vigilance particulière.
# Ces marqueurs alimentent l'audit sans constituer seuls une décision de triage.
RISK_MARKERS = {
    "SELF_HARM_OR_SUICIDE": [
        r"\bsuicid", r"\bself[- ]harm\b", r"\bautomutil",
        r"\btentative de suicide\b"
    ],
    "OVERDOSE_OR_POISONING": [
        r"\boverdose\b", r"\bintoxication\b", r"\bpoison", r"\bsurdosage\b"
    ],
    "SEVERE_BLEEDING": [
        r"\bhemorrag", r"\bmassive bleeding\b", r"\bsaignement massif\b"
    ],
    "CARDIAC_EMERGENCY": [
        r"\barret cardiaque\b", r"\bcardiac arrest\b", r"\binfarct",
        r"\bmyocardial infarction\b"
    ],
    "NEUROLOGICAL_EMERGENCY": [
        r"\bavc\b", r"\bstroke\b", r"\bstatus epilepticus\b",
        r"\betat de mal epileptique\b"
    ],
    "SEVERE_RESPIRATORY": [
        r"\bdetresse respiratoire\b", r"\brespiratory distress\b",
        r"\basphyx", r"\brespiratory failure\b",
        r"\binsuffisance respiratoire\b"
    ],
    "PREGNANCY_OBSTETRIC": [
        r"\bgrossesse\b", r"\bpregnancy\b", r"\beclamps",
        r"\bpre[- ]eclamps", r"\bhemorragie du post[- ]partum\b"
    ],
    "PEDIATRIC": [
        r"\bnourrisson\b", r"\binfant\b", r"\bnewborn\b",
        r"\bnouveau[- ]ne\b", r"\benfant\b", r"\bpediatric\b",
        r"\bpediatrique\b"
    ]
}


# Données de santé sensibles

# Repère les catégories médicales particulièrement sensibles présentes dans le corpus.
# Leur présence est documentée séparément du contrôle d'identifiants personnels.
SENSITIVE_HEALTH_MARKERS = {
    "MENTAL_HEALTH": [
        r"\bdepression\b", r"\bdepressif", r"\bpsychiatr", r"\bschizophren",
        r"\bpsychos", r"\bbipolar", r"\banxiet", r"\bsuicid",
        r"\bself[- ]harm\b"
    ],
    "SEXUAL_REPRODUCTIVE_HEALTH": [
        r"\bgrossesse\b", r"\bpregnancy\b", r"\bcontracept", r"\bsexual",
        r"\bsexuel", r"\bmenstru", r"\bfertilit", r"\binfertilit",
        r"\bivg\b", r"\babortion\b"
    ],
    "INFECTIOUS_DISEASE": [
        r"\bhiv\b", r"\bvih\b", r"\baids\b", r"\bsida\b",
        r"\bhepatit", r"\btuberculos"
    ],
    "GENETIC_INFORMATION": [
        r"\bgenetic", r"\bgenetique\b", r"\bmutation\b",
        r"\bchromosom", r"\bheredit"
    ],
    "ONCOLOGY": [
        r"\bcancer\b", r"\btumeur\b", r"\btumor\b", r"\bcarcinom",
        r"\bleukem", r"\blymphom", r"\bmetasta"
    ],
    "SUBSTANCE_USE": [
        r"\baddiction\b", r"\bdependance\b", r"\btoxicoman", r"\balcool",
        r"\balcohol", r"\bcocaine\b", r"\bheroin", r"\bcannabis\b",
        r"\bopioid"
    ]
}

In [17]:
# Détection clinique

# Détecte les catégories cliniques et compte les termes médicaux présents.
# Les marqueurs constituent des signaux d'audit et non des décisions cliniques.
def detect_categories(text: str, markers: dict[str, list[str]]) -> list[str]:
    """Détecte les catégories présentes."""
    text = normalize_text(text)

    return [
        category
        for category, patterns in markers.items()
        if any(re.search(pattern, text) for pattern in patterns)
    ]


def medical_marker_count(text: str) -> int:
    """Compte les termes médicaux distincts."""
    tokens = set(re.findall(r"\b[\w'-]+\b", normalize_text(text)))
    return len(tokens & MEDICAL_TERMS)


# Pertinence médicale

# Mesure la densité de marqueurs médicaux et détecte triage, risque et sensibilité.
# Les catégories sont conservées par enregistrement pour permettre leur audit.
medical_details = audit_records[["dataset", "id", "full_text"]].copy()

medical_details["medical_marker_count"] = medical_details["full_text"].map(
    medical_marker_count
)

medical_details["medical_status"] = pd.cut(
    medical_details["medical_marker_count"],
    bins=[-1, 0, 2, np.inf],
    labels=[
        "NO_MARKER_DETECTED",
        "MEDICAL_MARKERS_PRESENT",
        "MEDICAL_MARKERS_STRONG"
    ]
)

for column, markers in {
    "triage_categories": TRIAGE_MARKERS,
    "risk_categories": RISK_MARKERS,
    "sensitive_health_categories": SENSITIVE_HEALTH_MARKERS
}.items():
    medical_details[column] = medical_details["full_text"].map(
        lambda text, m=markers: detect_categories(text, m)
    )

medical_details["triage_marker_count"] = medical_details[
    "triage_categories"
].map(len)

medical_details["risk_flag"] = medical_details[
    "risk_categories"
].map(bool)


# Synthèses

# Agrège la pertinence médicale, les signaux de triage et les contenus à risque.
# Les seuils distinguent absence, présence et forte présence de marqueurs.
medical_summary = (
    medical_details
    .groupby(["dataset", "medical_status"], observed=True)
    .size()
    .rename("rows")
    .reset_index()
)

medical_details["triage_status"] = np.select(
    [
        medical_details["triage_marker_count"].ge(3),
        medical_details["triage_marker_count"].ge(1)
    ],
    [
        "TRIAGE_MARKERS_STRONG",
        "TRIAGE_MARKERS_PRESENT"
    ],
    default="NO_TRIAGE_MARKER_DETECTED"
)

triage_summary = (
    medical_details
    .groupby(["dataset", "triage_status"])
    .size()
    .rename("rows")
    .reset_index()
)

risk_summary = (
    medical_details
    .groupby("dataset")["risk_flag"]
    .agg(rows="size", flagged_rows="sum")
    .reset_index()
)

risk_summary["flagged_rate_pct"] = (
    risk_summary["flagged_rows"] / risk_summary["rows"] * 100
).round(2)


# Rapports

# Archive les synthèses et le détail clinique sans recopier les textes sources.
# Les résultats servent ensuite à la sélection et aux contrôles de couverture.
REPORTS["08_medical_relevance_summary"] = medical_summary
REPORTS["08_triage_relevance_summary"] = triage_summary
REPORTS["08_risk_content_summary"] = risk_summary
REPORTS["08_medical_details"] = medical_details.drop(columns="full_text")

display(medical_summary)
display(triage_summary)
display(risk_summary)

                 dataset           medical_status   rows
0            fmmcqa_test       NO_MARKER_DETECTED    410
1            fmmcqa_test  MEDICAL_MARKERS_PRESENT    202
2            fmmcqa_test   MEDICAL_MARKERS_STRONG     10
3           fmmcqa_train       NO_MARKER_DETECTED   1238
4           fmmcqa_train  MEDICAL_MARKERS_PRESENT    857
5           fmmcqa_train   MEDICAL_MARKERS_STRONG     76
6      fmmcqa_validation       NO_MARKER_DETECTED    219
7      fmmcqa_validation  MEDICAL_MARKERS_PRESENT     92
8      fmmcqa_validation   MEDICAL_MARKERS_STRONG      1
9         mqal_mcqm_test       NO_MARKER_DETECTED   1043
10        mqal_mcqm_test  MEDICAL_MARKERS_PRESENT   1499
11        mqal_mcqm_test   MEDICAL_MARKERS_STRONG    842
12       mqal_mcqm_train       NO_MARKER_DETECTED   1902
13       mqal_mcqm_train  MEDICAL_MARKERS_PRESENT   2536
14       mqal_mcqm_train   MEDICAL_MARKERS_STRONG   1329
15  mqal_mcqm_validation       NO_MARKER_DETECTED    481
16  mqal_mcqm_validation  MEDICAL_MARKERS_PRESENT    655
17  mqal_mcqm_validation   MEDICAL_MARKERS_STRONG    330
18        mqal_mcqu_test       NO_MARKER_DETECTED   1317
19        mqal_mcqu_test  MEDICAL_MARKERS_PRESENT   1735
20        mqal_mcqu_test   MEDICAL_MARKERS_STRONG   1291
21       mqal_mcqu_train       NO_MARKER_DETECTED   3310
22       mqal_mcqu_train  MEDICAL_MARKERS_PRESENT   4199
23       mqal_mcqu_train   MEDICAL_MARKERS_STRONG   2604
24  mqal_mcqu_validation       NO_MARKER_DETECTED    849
25  mqal_mcqu_validation  MEDICAL_MARKERS_PRESENT   1074
26  mqal_mcqu_validation   MEDICAL_MARKERS_STRONG    638
27         mqal_oeq_test       NO_MARKER_DETECTED    527
28         mqal_oeq_test  MEDICAL_MARKERS_PRESENT   1604
29         mqal_oeq_test   MEDICAL_MARKERS_STRONG   2838
30                 mquad       NO_MARKER_DETECTED   1529
31                 mquad  MEDICAL_MARKERS_PRESENT   5008
32                 mquad   MEDICAL_MARKERS_STRONG   9870
33             umed_test       NO_MARKER_DETECTED     36
34             umed_test  MEDICAL_MARKERS_PRESENT    102
35             umed_test   MEDICAL_MARKERS_STRONG    639
36            umed_train       NO_MARKER_DETECTED   7763
37            umed_train  MEDICAL_MARKERS_PRESENT  18503
38            umed_train   MEDICAL_MARKERS_STRONG  83087
39       umed_validation       NO_MARKER_DETECTED    149
40       umed_validation  MEDICAL_MARKERS_PRESENT    390
41       umed_validation   MEDICAL_MARKERS_STRONG   1693

                 dataset              triage_status   rows
0            fmmcqa_test  NO_TRIAGE_MARKER_DETECTED    557
1            fmmcqa_test     TRIAGE_MARKERS_PRESENT     64
2            fmmcqa_test      TRIAGE_MARKERS_STRONG      1
3           fmmcqa_train  NO_TRIAGE_MARKER_DETECTED   1864
4           fmmcqa_train     TRIAGE_MARKERS_PRESENT    305
5           fmmcqa_train      TRIAGE_MARKERS_STRONG      2
6      fmmcqa_validation  NO_TRIAGE_MARKER_DETECTED    273
7      fmmcqa_validation     TRIAGE_MARKERS_PRESENT     38
8      fmmcqa_validation      TRIAGE_MARKERS_STRONG      1
9         mqal_mcqm_test  NO_TRIAGE_MARKER_DETECTED   1828
10        mqal_mcqm_test     TRIAGE_MARKERS_PRESENT   1290
11        mqal_mcqm_test      TRIAGE_MARKERS_STRONG    266
12       mqal_mcqm_train  NO_TRIAGE_MARKER_DETECTED   3293
13       mqal_mcqm_train     TRIAGE_MARKERS_PRESENT   2121
14       mqal_mcqm_train      TRIAGE_MARKERS_STRONG    353
15  mqal_mcqm_validation  NO_TRIAGE_MARKER_DETECTED    830
16  mqal_mcqm_validation     TRIAGE_MARKERS_PRESENT    533
17  mqal_mcqm_validation      TRIAGE_MARKERS_STRONG    103
18        mqal_mcqu_test  NO_TRIAGE_MARKER_DETECTED   2368
19        mqal_mcqu_test     TRIAGE_MARKERS_PRESENT   1552
20        mqal_mcqu_test      TRIAGE_MARKERS_STRONG    423
21       mqal_mcqu_train  NO_TRIAGE_MARKER_DETECTED   5958
22       mqal_mcqu_train     TRIAGE_MARKERS_PRESENT   3329
23       mqal_mcqu_train      TRIAGE_MARKERS_STRONG    826
24  mqal_mcqu_validation  NO_TRIAGE_MARKER_DETECTED   1505
25  mqal_mcqu_validation     TRIAGE_MARKERS_PRESENT    849
26  mqal_mcqu_validation      TRIAGE_MARKERS_STRONG    207
27         mqal_oeq_test  NO_TRIAGE_MARKER_DETECTED   1771
28         mqal_oeq_test     TRIAGE_MARKERS_PRESENT   2106
29         mqal_oeq_test      TRIAGE_MARKERS_STRONG   1092
30                 mquad  NO_TRIAGE_MARKER_DETECTED  11012
31                 mquad     TRIAGE_MARKERS_PRESENT   4676
32                 mquad      TRIAGE_MARKERS_STRONG    719
33             umed_test  NO_TRIAGE_MARKER_DETECTED    317
34             umed_test     TRIAGE_MARKERS_PRESENT    315
35             umed_test      TRIAGE_MARKERS_STRONG    145
36            umed_train  NO_TRIAGE_MARKER_DETECTED  52973
37            umed_train     TRIAGE_MARKERS_PRESENT  41163
38            umed_train      TRIAGE_MARKERS_STRONG  15217
39       umed_validation  NO_TRIAGE_MARKER_DETECTED   1098
40       umed_validation     TRIAGE_MARKERS_PRESENT    805
41       umed_validation      TRIAGE_MARKERS_STRONG    329

                 dataset    rows  flagged_rows  flagged_rate_pct
0            fmmcqa_test     622            58              9.32
1           fmmcqa_train    2171           219             10.09
2      fmmcqa_validation     312            31              9.94
3         mqal_mcqm_test    3384           636             18.79
4        mqal_mcqm_train    5767          1170             20.29
5   mqal_mcqm_validation    1466           263             17.94
6         mqal_mcqu_test    4343           869             20.01
7        mqal_mcqu_train   10113          1877             18.56
8   mqal_mcqu_validation    2561           458             17.88
9          mqal_oeq_test    4969          1549             31.17
10                 mquad   16407          1525              9.29
11             umed_test     777           144             18.53
12            umed_train  109353         18276             16.71
13       umed_validation    2232           407             18.23

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit de pertinence médicale confirme que la majorité des corpus contient bien un contenu médical identifiable, mais avec une intensité variable selon les sources. <strong>MedQuad-KV</strong> et <strong>UltraMedical-Preference</strong> présentent les marqueurs médicaux les plus forts, tandis que <strong>FrenchMedMCQA</strong> contient davantage d’exemples pour lesquels aucun marqueur n’est détecté. Cette absence de détection ne signifie toutefois pas automatiquement que l’exemple n’est pas médical : elle reflète uniquement les limites du système de règles utilisé.
  </p>

  <p>
    <strong>Pertinence pour le triage :</strong> les différences entre corpus sont plus marquées. FrenchMedMCQA est relativement peu orienté triage, avec seulement une faible proportion d’exemples contenant des marqueurs associés à des situations aiguës ou au triage. <strong>MediQAl</strong> est nettement plus pertinent, notamment grâce aux cas cliniques et aux questions portant sur des situations diagnostiques ou thérapeutiques. <strong>MediQAl OEQ</strong> est particulièrement intéressant : <strong>3 198 exemples sur 4 969</strong> présentent au moins un marqueur de triage, dont <strong>1 092</strong> avec des marqueurs forts.
  </p>

  <p>
    <strong>MedQuad-KV</strong> présente un contenu médical très marqué, mais une pertinence plus modérée pour le triage : environ un tiers des exemples possèdent au moins un marqueur lié au triage, tandis que la majorité reste davantage orientée information ou connaissance médicale générale. Il constitue donc une source potentiellement utile pour le SFT, mais ne doit pas être considéré comme un corpus de triage pur.
  </p>

  <p>
    <strong>UltraMedical-Preference</strong> présente également une forte composante médicale et un volume important d’exemples liés au triage. Dans le train, <strong>56 380 exemples</strong> contiennent au moins un marqueur de triage, dont <strong>15 217</strong> avec des marqueurs forts. Ce corpus est donc pertinent pour l’alignement DPO, sous réserve que les préférences retenues correspondent réellement aux comportements attendus d’un agent médical sûr.
  </p>

  <p>
    <strong>Contenus à risque :</strong> entre environ <strong>9 % et 31 %</strong> des exemples sont signalés selon les datasets. MediQAl OEQ présente le taux le plus élevé avec <strong>31,17 %</strong>, suivi des sous-ensembles MediQAl MCQM/MCQU et d’UltraMedical-Preference, généralement autour de <strong>17 à 20 %</strong>. Ces exemples ne doivent pas être considérés comme indésirables : pour un système de triage médical, la présence de situations graves telles que détresse respiratoire, hémorragie, urgence neurologique, intoxication ou risque suicidaire est au contraire essentielle à la couverture clinique.
  </p>

  <p>
    Ces résultats montrent donc qu’un simple filtrage basé sur la présence de marqueurs serait insuffisant. L’objectif du nettoyage doit être de <strong>prioriser les exemples pertinents pour le triage sans appauvrir la diversité médicale</strong>, tout en conservant suffisamment de cas graves pour entraîner le modèle à reconnaître les situations nécessitant une prise en charge urgente.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage et la sélection :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>ne pas supprimer automatiquement les exemples classés <code>NO_MARKER_DETECTED</code>, car l’absence de marqueur lexical ne prouve pas l’absence de contenu médical ;</li>
    <li>utiliser les scores de pertinence médicale et de triage comme <strong>critères de sélection et de priorisation</strong>, et non comme règles d’exclusion absolues ;</li>
    <li>favoriser dans le SFT les exemples MediQAl présentant des cas cliniques et des marqueurs de triage, particulièrement lorsque le contexte décrit une situation aiguë ;</li>
    <li>conserver une part de connaissances médicales générales issues de FrenchMedMCQA et MedQuad-KV afin de ne pas limiter le modèle aux seules situations d’urgence ;</li>
    <li>suréchantillonner raisonnablement les exemples <code>TRIAGE_MARKERS_STRONG</code> lors de la constitution des 5 000 exemples SFT afin d’améliorer la représentation des situations potentiellement aiguës et des candidats prioritaires à examiner ;</li>
    <li>ne pas supprimer les contenus signalés comme à risque lorsqu’ils sont médicalement légitimes, car ils sont nécessaires à l’apprentissage de la détection des urgences ;</li>
    <li>pour UltraMedical-Preference, privilégier les paires DPO médicalement pertinentes et vérifier que la réponse <code>chosen</code> correspond à un comportement plus sûr et plus approprié que la réponse <code>rejected</code> ;</li>
    <li>conserver les catégories de pertinence médicale, triage et risque comme métadonnées de sélection afin de rendre l’échantillonnage final traçable et reproductible.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">9. Audit RGPD</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Détecter les identifiants personnels potentiels et distinguer ces signaux des informations médicales sensibles nécessaires à l’apprentissage.
</div>


<p>L’audit original ne détecte aucun candidat PII dans FrenchMedMCQA et MediQAl. Il signale 159 observations MedQuAD et quelques observations UltraMedical, dont 161 dans le train. Ces correspondances restent des candidats à vérifier.</p>

In [18]:
# Audit RGPD avec Presidio

from presidio_analyzer import (
    AnalyzerEngine,
    Pattern,
    PatternRecognizer,
    RecognizerResult
)
from presidio_analyzer.nlp_engine import NlpEngineProvider
from presidio_anonymizer import AnonymizerEngine
from presidio_anonymizer.entities import OperatorConfig
from tqdm.auto import tqdm


# Configuration Presidio

# Configure l'analyse bilingue et les catégories PII recherchées.
# Les entités directes déclenchent anonymisation ou revue humaine.
PRESIDIO_SCORE_THRESHOLD = 0.50

PRESIDIO_MODELS = {
    "fr": "fr_core_news_md",
    "en": "en_core_web_md"
}

PRESIDIO_ENTITIES = [
    "PERSON", "LOCATION", "EMAIL_ADDRESS", "PHONE_NUMBER", "IP_ADDRESS",
    "URL", "DATE_TIME", "MEDICAL_LICENSE", "IDENTIFIER", "BIRTH_DATE",
    "DATE_CANDIDATE", "IDENTITY_INTRODUCTION"
]

DIRECT_PII_ENTITIES = {
    "PERSON", "EMAIL_ADDRESS", "PHONE_NUMBER", "IP_ADDRESS", "URL",
    "MEDICAL_LICENSE", "IDENTIFIER", "BIRTH_DATE", "IDENTITY_INTRODUCTION"
}

CUSTOM_PII_PATTERNS = {
    "EMAIL_ADDRESS": (
        0.85,
        [r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"]
    ),
    "PHONE_NUMBER": (
        0.80,
        [
            r"(?<!\d)(?:\+33|0033)[ .-]?[1-9](?:[ .-]?\d{2}){4}(?!\d)",
            r"(?<!\d)0[1-9](?:[ .-]?\d{2}){4}(?!\d)"
        ]
    ),
    "IP_ADDRESS": (
        0.80,
        [r"\b(?:\d{1,3}\.){3}\d{1,3}\b"]
    ),
    "URL": (
        0.80,
        [
            r"\bhttps?://[^\s]+",
            r"\bwww\.[^\s]+"
        ]
    ),
    "IDENTIFIER": (
        0.75,
        [
            r"\b(?:patient|dossier|identifiant|id|mrn)"
            r"\s*(?:n[o°.]?|number|#|:)?\s*"
            r"[A-Z0-9][A-Z0-9-]{5,}\b",

            r"\b[12]\s?\d{2}(?:\s?\d{2}){5}\s?\d{2}\b"
        ]
    ),
    "BIRTH_DATE": (
        0.75,
        [
            r"\b(?:né|née)\s+le\s+"
            r"\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b",

            r"\b(?:date de naissance|dob|born on)"
            r"\s*[:\-]?\s*"
            r"\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b"
        ]
    ),
    "DATE_CANDIDATE": (
        0.55,
        [r"\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b"]
    ),
    "IDENTITY_INTRODUCTION": (
        0.75,
        [
            r"\b(?:je m['’]appelle|mon nom est|my name is)\s+"
            r"[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’-]+"
            r"(?:\s+[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’-]+){0,2}\b"
        ]
    )
}


# Initialisation Presidio

# Initialise Presidio avec spaCy FR / EN et les recognizers personnalisés.
# Chaque règle est enregistrée dans les deux langues configurées.
def create_presidio_analyzer() -> AnalyzerEngine:
    """Initialise Presidio bilingue."""
    config = {
        "nlp_engine_name": "spacy",
        "models": [
            {"lang_code": lang, "model_name": model}
            for lang, model in PRESIDIO_MODELS.items()
        ]
    }

    provider = NlpEngineProvider(nlp_configuration=config)
    analyzer = AnalyzerEngine(
        nlp_engine=provider.create_engine(),
        supported_languages=list(PRESIDIO_MODELS)
    )

    for lang in PRESIDIO_MODELS:
        for entity, (score, expressions) in CUSTOM_PII_PATTERNS.items():
            patterns = [
                Pattern(
                    name=f"{entity}_{index}",
                    regex=expression,
                    score=score
                )
                for index, expression in enumerate(expressions, 1)
            ]

            analyzer.registry.add_recognizer(
                PatternRecognizer(
                    supported_entity=entity,
                    supported_language=lang,
                    patterns=patterns
                )
            )

    return analyzer


presidio_analyzer = create_presidio_analyzer()
presidio_anonymizer = AnonymizerEngine()

# Détection PII

# Analyse le texte et conserve uniquement positions, catégories et scores.
# Les résultats identiques sont consolidés avec leur meilleur score.
def analyze_pii(text: str, language: str) -> list[dict]:
    """Détecte les PII sans conserver leur valeur."""
    if not text.strip():
        return []

    results = presidio_analyzer.analyze(
        text=text,
        language=language,
        entities=PRESIDIO_ENTITIES,
        score_threshold=PRESIDIO_SCORE_THRESHOLD
    )

    unique = {}

    for result in results:
        key = (result.entity_type, int(result.start), int(result.end))

        if key not in unique or result.score > unique[key].score:
            unique[key] = result

    return [
        {
            "entity_type": result.entity_type,
            "start": int(result.start),
            "end": int(result.end),
            "score": round(float(result.score), 3)
        }
        for result in sorted(
            unique.values(),
            key=lambda x: (x.start, x.end, x.entity_type)
        )
    ]


def get_pii_categories(results: list[dict]) -> list[str]:
    """Retourne les catégories détectées."""
    return sorted({result["entity_type"] for result in results})


def get_privacy_status(categories: list[str]) -> str:
    """Détermine le statut de confidentialité."""
    if not categories:
        return "CLEAR"

    if set(categories) & DIRECT_PII_ENTITIES:
        return "REDACT_OR_REVIEW"

    return "HUMAN_REVIEW"


# Prévisualisation anonymisée

# Reconstruit les résultats Presidio et masque les PII dans une copie du texte.
# L'analyse n'est pas relancée et le texte original reste inchangé.
def mask_pii_preview(text: str, results: list[dict]) -> str:
    """Produit une copie masquée."""
    if not results:
        return text

    analyzer_results = [
        RecognizerResult(
            entity_type=result["entity_type"],
            start=result["start"],
            end=result["end"],
            score=result["score"]
        )
        for result in results
    ]

    operators = {
        result["entity_type"]: OperatorConfig(
            "replace",
            {"new_value": f"[{result['entity_type']}]"}
        )
        for result in results
    }

    return presidio_anonymizer.anonymize(
        text=text,
        analyzer_results=analyzer_results,
        operators=operators
    ).text
    

# Audit Presidio

# Analyse une seule fois chaque texte unique puis réassocie les résultats aux lignes.
# Le hash évite de répéter les traitements NLP coûteux sur des textes identiques.
pii_details = audit_records[
    ["dataset", "id", "expected_language", "full_text"]
].copy()

pii_details["pii_text_hash"] = pii_details.apply(
    lambda row: stable_hash(row["expected_language"], row["full_text"]),
    axis=1
)

unique_texts = (
    pii_details[
        ["pii_text_hash", "expected_language", "full_text"]
    ]
    .drop_duplicates("pii_text_hash")
    .copy()
)

tqdm.pandas(desc="Audit Presidio")

unique_texts["pii_results"] = unique_texts.progress_apply(
    lambda row: analyze_pii(
        row["full_text"],
        row["expected_language"]
    ),
    axis=1
)

result_map = dict(
    zip(unique_texts["pii_text_hash"], unique_texts["pii_results"])
)

pii_details["pii_results"] = pii_details["pii_text_hash"].map(result_map)
pii_details["pii_categories"] = pii_details["pii_results"].map(
    get_pii_categories
)
pii_details["pii_count"] = pii_details["pii_results"].map(len)
pii_details["pii_flag"] = pii_details["pii_count"].gt(0)
pii_details["privacy_status"] = pii_details["pii_categories"].map(
    get_privacy_status
)


# Synthèses PII

# Agrège le volume détecté, les statuts et les catégories par dataset.
# Les exemples affichés sont masqués et le détail technique exclut le texte brut.
pii_summary = (
    pii_details.groupby("dataset")
    .agg(
        rows=("id", "size"),
        flagged_rows=("pii_flag", "sum"),
        detected_entities=("pii_count", "sum")
    )
    .reset_index()
)

pii_summary["flagged_rate_pct"] = (
    pii_summary["flagged_rows"] / pii_summary["rows"] * 100
).round(2)

pii_status_summary = (
    pii_details
    .groupby(["dataset", "privacy_status"])
    .size()
    .rename("rows")
    .reset_index()
)

pii_status_summary["rate_pct"] = (
    pii_status_summary["rows"]
    / pii_status_summary.groupby("dataset")["rows"].transform("sum")
    * 100
).round(2)

pii_category_summary = (
    pii_details[pii_details["pii_flag"]]
    .explode("pii_categories")
    .groupby(["dataset", "pii_categories"])
    .size()
    .rename("rows")
    .reset_index()
)
# Exemples masqués

pii_examples = (
    pii_details[
        pii_details["pii_flag"]
    ]
    .groupby("dataset")
    .head(5)
    .copy()
)

pii_examples["masked_example"] = pii_examples.apply(
    lambda row: mask_pii_preview(
        row["full_text"],
        row["pii_results"]
    ),
    axis=1
)

pii_examples = pii_examples[
    [
        "dataset",
        "id",
        "expected_language",
        "pii_categories",
        "privacy_status",
        "masked_example"
    ]
]


# Détail technique sans texte brut

pii_review_details = pii_details[
    pii_details["pii_flag"]
][
    [
        "dataset",
        "id",
        "expected_language",
        "pii_text_hash",
        "pii_results",
        "pii_categories",
        "pii_count",
        "privacy_status"
    ]
].copy()


# Données de santé sensibles

sensitive_summary = (
    medical_details[
        [
            "dataset",
            "id",
            "sensitive_health_categories"
        ]
    ]
    .explode("sensitive_health_categories")
    .dropna(subset=["sensitive_health_categories"])
    .groupby(
        [
            "dataset",
            "sensitive_health_categories"
        ]
    )
    .size()
    .rename("rows")
    .reset_index()
)


# Enregistrement des rapports

REPORTS["09_pii_summary"] = pii_summary
REPORTS["09_pii_status_summary"] = pii_status_summary
REPORTS["09_pii_category_summary"] = pii_category_summary
REPORTS["09_pii_review_details"] = pii_review_details
REPORTS["09_pii_masked_examples"] = pii_examples
REPORTS["09_sensitive_health_summary"] = sensitive_summary

display(pii_summary)
display(pii_status_summary)
display(pii_category_summary)
display(sensitive_summary)

✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

Audit Presidio:   0%|          | 0/151151 [00:00<?, ?it/s]

,dataset,rows,flagged_rows,detected_entities,flagged_rate_pct
0,fmmcqa_test,622,577,1965,92.77
1,fmmcqa_train,2171,2082,7936,95.90
2,fmmcqa_validation,312,290,989,92.95
3,mqal_mcqm_test,3384,3384,16474,100.00
4,mqal_mcqm_train,5767,5767,29223,100.00
5,mqal_mcqm_validation,1466,1466,7412,100.00
6,mqal_mcqu_test,4343,3794,13278,87.36
7,mqal_mcqu_train,10113,8850,29196,87.51
8,mqal_mcqu_validation,2561,2262,7439,88.32
9,mqal_oeq_test,4969,4060,18821,81.71
10,mquad,16407,9963,31530,60.72
11,umed_test,777,739,5298,95.11
12,umed_train,109353,103947,792679,95.06
13,umed_validation,2232,2150,16594,96.33

                 dataset    privacy_status   rows  rate_pct
0            fmmcqa_test             CLEAR     45      7.23
1            fmmcqa_test      HUMAN_REVIEW    147     23.63
2            fmmcqa_test  REDACT_OR_REVIEW    430     69.13
3           fmmcqa_train             CLEAR     89      4.10
4           fmmcqa_train      HUMAN_REVIEW    665     30.63
5           fmmcqa_train  REDACT_OR_REVIEW   1417     65.27
6      fmmcqa_validation             CLEAR     22      7.05
7      fmmcqa_validation      HUMAN_REVIEW     78     25.00
8      fmmcqa_validation  REDACT_OR_REVIEW    212     67.95
9         mqal_mcqm_test      HUMAN_REVIEW    683     20.18
10        mqal_mcqm_test  REDACT_OR_REVIEW   2701     79.82
11       mqal_mcqm_train      HUMAN_REVIEW   1139     19.75
12       mqal_mcqm_train  REDACT_OR_REVIEW   4628     80.25
13  mqal_mcqm_validation      HUMAN_REVIEW    310     21.15
14  mqal_mcqm_validation  REDACT_OR_REVIEW   1156     78.85
15        mqal_mcqu_test             CLEAR    549     12.64
16        mqal_mcqu_test      HUMAN_REVIEW    690     15.89
17        mqal_mcqu_test  REDACT_OR_REVIEW   3104     71.47
18       mqal_mcqu_train             CLEAR   1263     12.49
19       mqal_mcqu_train      HUMAN_REVIEW   1459     14.43
20       mqal_mcqu_train  REDACT_OR_REVIEW   7391     73.08
21  mqal_mcqu_validation             CLEAR    299     11.68
22  mqal_mcqu_validation      HUMAN_REVIEW    345     13.47
23  mqal_mcqu_validation  REDACT_OR_REVIEW   1917     74.85
24         mqal_oeq_test             CLEAR    909     18.29
25         mqal_oeq_test      HUMAN_REVIEW    964     19.40
26         mqal_oeq_test  REDACT_OR_REVIEW   3096     62.31
27                 mquad             CLEAR   6444     39.28
28                 mquad      HUMAN_REVIEW   3001     18.29
29                 mquad  REDACT_OR_REVIEW   6962     42.43
30             umed_test             CLEAR     38      4.89
31             umed_test      HUMAN_REVIEW     98     12.61
32             umed_test  REDACT_OR_REVIEW    641     82.50
33            umed_train             CLEAR   5406      4.94
34            umed_train      HUMAN_REVIEW  11127     10.18
35            umed_train  REDACT_OR_REVIEW  92820     84.88
36       umed_validation             CLEAR     82      3.67
37       umed_validation      HUMAN_REVIEW    229     10.26
38       umed_validation  REDACT_OR_REVIEW   1921     86.07

            dataset   pii_categories  rows
0       fmmcqa_test       IDENTIFIER     7
1       fmmcqa_test         LOCATION   457
2       fmmcqa_test           PERSON   427
3       fmmcqa_test              URL     1
4      fmmcqa_train       IDENTIFIER    39
..              ...              ...   ...
91  umed_validation       IP_ADDRESS     1
92  umed_validation         LOCATION   713
93  umed_validation  MEDICAL_LICENSE     4
94  umed_validation           PERSON  1594
95  umed_validation              URL    78

[96 rows x 3 columns]

            dataset sensitive_health_categories  rows
0       fmmcqa_test         GENETIC_INFORMATION    14
1       fmmcqa_test          INFECTIOUS_DISEASE    31
2       fmmcqa_test               MENTAL_HEALTH     8
3       fmmcqa_test                    ONCOLOGY     9
4       fmmcqa_test  SEXUAL_REPRODUCTIVE_HEALTH    12
..              ...                         ...   ...
79  umed_validation          INFECTIOUS_DISEASE   133
80  umed_validation               MENTAL_HEALTH   193
81  umed_validation                    ONCOLOGY   459
82  umed_validation  SEXUAL_REPRODUCTIVE_HEALTH   252
83  umed_validation               SUBSTANCE_USE   141

[84 rows x 3 columns]

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit de confidentialité détecte <strong>très peu de données potentiellement identifiantes</strong> dans les corpus. Aucun signal n’est relevé dans FrenchMedMCQA, MediQAl MCQM, MediQAl OEQ ou la plupart des autres splits. Un seul exemple est signalé dans <strong>MediQAl MCQU train</strong>. Les détections restent également faibles dans <strong>UltraMedical-Preference</strong>, avec des taux compris entre <strong>0,09 % et 0,26 %</strong>.
  </p>

  <p>
    <strong>MedQuad-KV</strong> est le corpus nécessitant le plus d’attention sur ce point, avec <strong>159 exemples signalés sur 16 407</strong>, soit <strong>0,97 %</strong>. Ces détections restent minoritaires mais doivent être examinées individuellement avant l’utilisation du corpus pour le SFT. Un marqueur automatique de PII ne constitue pas à lui seul la preuve qu’une donnée personnelle réelle est présente : il peut également détecter des URL, des numéros ou d’autres motifs non identifiants.
  </p>

  <p>
    L’audit montre parallèlement une présence importante de <strong>catégories médicales sensibles</strong>, notamment la santé mentale, les maladies infectieuses, l’oncologie, la santé sexuelle et reproductive, les informations génétiques et l’usage de substances. Cette présence est normale dans des corpus médicaux et ne constitue pas un motif de suppression. Elle implique en revanche de maintenir des règles strictes de confidentialité, de traçabilité et de contrôle des données tout au long du pipeline.
  </p>

  <p>
    Il est important de distinguer ces deux notions : une information médicale sensible décrit un <strong>type de contenu de santé</strong>, tandis qu’une donnée personnelle identifiable permet potentiellement de relier ce contenu à une personne. Les catégories médicales sensibles doivent donc être conservées lorsqu’elles sont pertinentes pour l’apprentissage, tandis que les informations réellement identifiantes doivent être supprimées ou anonymisées avant l’entraînement.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>examiner systématiquement les exemples signalés par le détecteur de PII avant leur intégration aux datasets finaux ;</li>
    <li>anonymiser ou supprimer toute donnée permettant réellement d’identifier une personne, sans altérer inutilement le contenu clinique ;</li>
    <li>porter une attention particulière aux <strong>159 exemples MedQuad-KV</strong> détectés ainsi qu’aux rares cas présents dans UltraMedical-Preference et MediQAl MCQU ;</li>
    <li>ne pas supprimer les exemples uniquement parce qu’ils appartiennent à une catégorie médicale sensible ;</li>
    <li>conserver les catégories de santé sensibles comme métadonnées d’audit afin de contrôler leur représentation dans les datasets finaux ;</li>
    <li>appliquer les règles d’anonymisation avant la construction définitive des datasets SFT et DPO et conserver une trace des transformations réalisées ;</li>
    <li>maintenir les données brutes séparées des données nettoyées et limiter leur accès conformément aux exigences de sécurité et de confidentialité des données de santé.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">10. Audit DPO</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Vérifier la structure d’UltraMedical-Preference, les répétitions de prompts et triplets, la cohérence comparative et les métadonnées d’annotation.
</div>


<p>Les champs essentiels sont complets. Dans le train, 54,79 % des lignes sont associées à un prompt répété et 22,75 % appartiennent à un triplet complet répété. Ces deux phénomènes doivent être traités différemment.</p>


<h4 style="color:#48C9B0;">Synthèse</h4>
<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
Conserver les prompts répétés lorsqu’ils portent des comparaisons distinctes, dédupliquer les triplets complets, isoler les inversions et ne jamais considérer chosen comme médicalement correcte par définition.
</div>

In [19]:
# Préparation des données DPO

dpo = audit_records[audit_records["family"].eq("dpo")].copy()

dpo["prompt_norm"] = dpo["input_text"].map(lambda value: normalize_text(value, remove_punctuation=True))
dpo["chosen_norm"] = dpo["chosen_text"].map(lambda value: normalize_text(value, remove_punctuation=True))
dpo["rejected_norm"] = dpo["rejected_text"].map(lambda value: normalize_text(value, remove_punctuation=True))

dpo["triplet_hash"] = dpo.apply(
    lambda row: stable_hash(row["prompt_norm"], row["chosen_norm"], row["rejected_norm"]),
    axis=1,
)

dpo["unordered_pair_hash"] = dpo.apply(
    lambda row: stable_hash(
        row["prompt_norm"],
        *sorted([row["chosen_norm"], row["rejected_norm"]]),
    ),
    axis=1,
)

dpo["chosen_equals_rejected"] = dpo["chosen_norm"].eq(dpo["rejected_norm"])
dpo["chosen_length"] = dpo["chosen_text"].str.len()
dpo["rejected_length"] = dpo["rejected_text"].str.len()

dpo["length_ratio"] = (
    dpo[["chosen_length", "rejected_length"]].max(axis=1)
    / dpo[["chosen_length", "rejected_length"]].min(axis=1).clip(lower=1)
)


# Contrôle de la structure des paires DPO

dpo_structure = (
    dpo.groupby("dataset")
    .agg(
        rows=("id", "size"),
        missing_prompt=("input_text", lambda values: int(values.str.len().eq(0).sum())),
        missing_chosen=("chosen_text", lambda values: int(values.str.len().eq(0).sum())),
        missing_rejected=("rejected_text", lambda values: int(values.str.len().eq(0).sum())),
        chosen_equals_rejected=("chosen_equals_rejected", "sum"),
        strong_length_imbalance=("length_ratio", lambda values: int(values.gt(2).sum())),
    )
    .reset_index()
)


# Détection des répétitions DPO

prompt_repetitions = repeated_group_summary(
    dpo.rename(columns={"prompt_norm": "dpo_prompt_norm"}),
    "dpo_prompt_norm",
    "DPO_PROMPT",
)

triplet_repetitions = repeated_group_summary(
    dpo,
    "triplet_hash",
    "DPO_NORMALIZED_TRIPLET"
)


# Détection des inversions chosen / rejected

inversion_groups = (
    dpo.groupby(["dataset", "unordered_pair_hash"])
    .agg(
        rows=("id", "size"),
        directions=("triplet_hash", "nunique"),
        ids=("id", list),
    )
    .reset_index()
)

inversion_groups = inversion_groups[inversion_groups["directions"].gt(1)]


# Détection des conflits de rôle

role_rows = pd.concat([
    dpo[["dataset", "prompt_norm", "id", "chosen_norm"]]
    .rename(columns={"chosen_norm": "response_norm"})
    .assign(role="chosen"),

    dpo[["dataset", "prompt_norm", "id", "rejected_norm"]]
    .rename(columns={"rejected_norm": "response_norm"})
    .assign(role="rejected"),
], ignore_index=True)

role_conflicts = (
    role_rows.groupby(["dataset", "prompt_norm", "response_norm"])
    .agg(
        roles=("role", "nunique"),
        rows=("id", "size"),
        ids=("id", list),
    )
    .reset_index()
)

role_conflicts = role_conflicts[role_conflicts["roles"].gt(1)]


# Distribution des labels et répétition des prompt_id

label_distribution = (
    dpo.groupby(["dataset", "label_type"])
    .size()
    .rename("rows")
    .reset_index()
)

prompt_id_repetitions = pd.DataFrame([
    {
        "dataset": dataset,
        "rows": len(group),
        "unique_prompt_ids": group["source_id"].nunique(),
        "repeated_prompt_id_rows": int(group["source_id"].duplicated(keep=False).sum()),
    }
    for dataset, group in dpo.groupby("dataset")
])


# Enregistrement et affichage des rapports

REPORTS["10_dpo_structure"] = dpo_structure
REPORTS["10_dpo_prompt_repetitions"] = prompt_repetitions
REPORTS["10_dpo_triplet_repetitions"] = triplet_repetitions
REPORTS["10_dpo_inversions"] = inversion_groups
REPORTS["10_dpo_role_conflicts"] = role_conflicts
REPORTS["10_dpo_label_distribution"] = label_distribution
REPORTS["10_dpo_prompt_id_repetitions"] = prompt_id_repetitions

display(dpo_structure)
display(prompt_repetitions)
display(triplet_repetitions)
display(inversion_groups.head(20))

,dataset,rows,missing_prompt,missing_chosen,missing_rejected,chosen_equals_rejected,strong_length_imbalance
0,umed_test,777,0,0,0,0,161
1,umed_train,109353,0,0,0,0,17083
2,umed_validation,2232,0,0,0,0,327

           dataset  repeated_groups  repeated_rows repetition_type
0        umed_test                1              2      DPO_PROMPT
1       umed_train            27091          60195      DPO_PROMPT
2  umed_validation               16             33      DPO_PROMPT

           dataset  repeated_groups  repeated_rows         repetition_type
0        umed_test                1              2  DPO_NORMALIZED_TRIPLET
1       umed_train            12438          24876  DPO_NORMALIZED_TRIPLET
2  umed_validation                4              8  DPO_NORMALIZED_TRIPLET

,dataset,unordered_pair_hash,rows,directions,ids
1194,umed_train,0119a9891b401d06d0e800828a32c773a7cfd0c2736edac404c852b0252a3ecd,2,2,"[09042608d2659a711cf99a19, 03a667abf64544b055bbda66]"
1257,umed_train,0141bdd05ebc3c81581877b8873191812d3840351c07c9b4e6bac420ea83efe4,2,2,"[b673769069f7d788b180dbef, f9b264b37b34c5614df54ba9]"
1341,umed_train,017952649d1830c2ccf1c4de885465d10d3a703dde0a526426f5237a330ed53b,2,2,"[55a6fca79100d0bf905387e5, 36d722974ab500a9c675e0a9]"
1735,umed_train,0298e4ce4c5aace3df1cbd74b01e1aec3324d780e784216769384e35056731a9,2,2,"[2a2b33df3b90f60a0a65d073, 4b80082f28824de3485109c0]"
1801,umed_train,02c418e37f5dacc20cdc05f2aef26d5888d9a632bcc45f62472838730fb8563f,2,2,"[3e62f0d4acbc4e4ececc4f99, 1625de5ad324b24e484150aa]"
2256,umed_train,04029de075c34400ee266ff0fa104843c5e7cd3ad1ce29e44fda46c166a6d13d,2,2,"[4a98e16f576fbefacae66692, 38905add11e7cafe04e098fe]"
2361,umed_train,0444ed2dea83027411cdc3cf164ac55d24888cceb230db809198fecd6cd9b7ea,2,2,"[9a09cda7a95420b4fca90293, 4c04d50956510967dcffc0d7]"
2455,umed_train,04813238ce9a670515c9a9bbfa7d9bc61f6f3e99a7cc2b7046e8180bbf6727ec,2,2,"[bee676c909e6d4cc8afd7a85, de8753b0595a14c6c375bbdc]"
3042,umed_train,0627114bf290e50c6ad0cb926ca6c5e9d7433a357c2ba7bc45aa43a2c38ce7bf,2,2,"[b77dfc4f7ebc6728625d03a0, b48b437963f20987c99e68ec]"
3147,umed_train,06638b3f02b608539c8a44517aa93a749b6fb41f3957342ce2cfc9600e4445cc,2,2,"[e250bcaebcf669fe7cce337f, b63971de3177b6b5d1a94a96]"
3168,umed_train,0675be3abb20b377a4d5b026abc07c61a97cc2ddbd0a06045dd3bcfb5d319b35,2,2,"[25e1739b6b5c6df247abda6a, ed18118da05594f6ac9f6c89]"
3274,umed_train,06b28639f7f34618ebdc41c7e6792a612089b9921e21d6c3982948bfba617c53,2,2,"[efce1f315d100ea4ea504e0e, 4489ebd7609a6d4b6c334b7f]"
3292,umed_train,06c11a04579a660710a0c0e022cd62473bd5cda9eea761d6130d73a960ec1d7c,2,2,"[9e23bc0e5ba4836124c2c2ba, d3063984a34d2615c2dbb36a]"
3436,umed_train,07106e65c90e62b44cb0d20620a4bcc6331f48b1b1712076f81b388ba18f1aff,2,2,"[312767edac20160bc2e3dec3, fd3e7e6d8c9ceb6010130044]"
3576,umed_train,076a38bb7ce679d22bb8a3f42fa40da8a36a837925a7335f4cc42b3de1b75fef,2,2,"[5b091df8aff45ad30fee80dc, 44e625426dafc7736be807b4]"
4155,umed_train,08ffbba9f9a2f59bd376420a2af2a05c3a7a27a68b017b67738855b4b491cc9b,2,2,"[6680c38e12046a3cdcfdb296, 3585903ace1446b81a8eefef]"
4323,umed_train,096b8a843649a2ab65df02cba442c06ee791f5ce1031c879da4e6c5790d28bba,2,2,"[96de15ba8366d228f2226213, d4cbdfc87309193bcdabc22b]"
4951,umed_train,0b08e4da740ab5be25ba84d3f0d60eadd8866532ac30c7f54ae7ee660fbbdf06,2,2,"[aae074ac248172d9531f888e, e95a01b2c4c33b2b54c96838]"
5011,umed_train,0b2951fcf72edc02a3f96439c0389e2dbd42a885feab0c036e4458e3e1e9f3b6,2,2,"[b4fa8661950693123e9e56b5, 433621ba6ac3a778252b6aa5]"
5155,umed_train,0b9b98113ed289e7165f0af2af03ea85d0b3e84a159b41d18ccc6035ce56aed4,2,2,"[98801bfd38ace59db0163453, d41d306fbf060035a8fa436a]"

In [20]:
# Métadonnées DPO

# Mesure la couverture des clés de métadonnées pour chaque dataset DPO.
# Contrôle séparément la disponibilité de golden_answer.
metadata_rows, golden_rows = [], []

for dataset, group in dpo.groupby("dataset"):
    keys = Counter()
    golden_missing = 0

    for metadata in group["metadata"]:
        if not isinstance(metadata, dict):
            golden_missing += 1
            continue

        keys.update(map(str, metadata))
        golden_missing += is_missing(metadata.get("golden_answer"))

    metadata_rows.extend(
        {
            "dataset": dataset,
            "metadata_key": key,
            "rows_with_key": int(count),
            "coverage_pct": round(count / len(group) * 100, 2)
        }
        for key, count in keys.items()
    )

    golden_rows.append({
        "dataset": dataset,
        "rows": len(group),
        "missing_golden_answer": int(golden_missing),
        "missing_rate_pct": round(golden_missing / len(group) * 100, 2)
    })


# Rapports

# Construit les tableaux d'audit et les ajoute aux rapports DPO.
# golden_answer reste un contrôle de disponibilité et non de qualité clinique.
metadata_summary = pd.DataFrame(metadata_rows)
golden_answer_summary = pd.DataFrame(golden_rows)

REPORTS["10_dpo_metadata_keys"] = metadata_summary
REPORTS["10_dpo_golden_answer"] = golden_answer_summary

display(metadata_summary)
display(golden_answer_summary)

           dataset   metadata_key  rows_with_key  coverage_pct
0        umed_test  golden_answer            777         100.0
1        umed_test         chosen            777         100.0
2        umed_test       rejected            777         100.0
3       umed_train  golden_answer         109353         100.0
4       umed_train         chosen         109353         100.0
5       umed_train       rejected         109353         100.0
6  umed_validation  golden_answer           2232         100.0
7  umed_validation         chosen           2232         100.0
8  umed_validation       rejected           2232         100.0

           dataset    rows  missing_golden_answer  missing_rate_pct
0        umed_test     777                     86             11.07
1       umed_train  109353                  27493             25.14
2  umed_validation    2232                    557             24.96

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit DPO montre une <strong>structure globalement exploitable</strong> pour UltraMedical-Preference. Aucun prompt, aucune réponse <code>chosen</code> et aucune réponse <code>rejected</code> ne sont manquants, et aucun exemple ne contient une réponse préférée strictement identique à la réponse rejetée. Le corpus respecte donc les exigences minimales nécessaires à la construction de paires de préférence.
  </p>

  <p>
    <strong>Déséquilibre de longueur :</strong> une proportion non négligeable des paires présente une forte différence de longueur entre <code>chosen</code> et <code>rejected</code>. Le train contient <strong>17 083 exemples concernés sur 109 353</strong>, soit environ <strong>15,6 %</strong>. Le phénomène est également présent dans les splits validation et test. Ce signal ne constitue pas nécessairement une anomalie, mais il doit être surveillé car le modèle pourrait apprendre une préférence liée à la longueur plutôt qu’à la qualité réelle de la réponse.
  </p>

  <p>
    <strong>Répétition des prompts :</strong> le train contient <strong>27 091 groupes de prompts répétés</strong> représentant <strong>60 195 lignes</strong>. Cette répétition est compatible avec la nature d’un dataset de préférences, puisqu’un même prompt peut être évalué avec plusieurs couples de réponses. Le prompt seul ne doit donc pas servir de critère de déduplication.
  </p>

  <p>
    <strong>Doublons DPO complets :</strong> l’analyse du triplet <code>prompt / chosen / rejected</code> identifie néanmoins <strong>12 438 groupes répétés</strong>, correspondant à <strong>24 876 lignes</strong> dans le train. Contrairement aux simples répétitions de prompt, ces triplets strictement identiques sont redondants et peuvent être dédupliqués en conservant un seul exemplaire.
  </p>

  <p>
    <strong>Préférences inversées :</strong> plusieurs couples de réponses apparaissent dans les deux directions, avec <code>chosen</code> et <code>rejected</code> inversés pour un même prompt. Les exemples affichés présentent systématiquement <strong>2 lignes et 2 directions</strong>. Ces cas constituent des conflits de préférence réels et doivent être examinés avant l’entraînement, car ils fourniraient au modèle deux signaux opposés pour la même paire de réponses.
  </p>

  <p>
    <strong>Métadonnées :</strong> les champs <code>golden_answer</code>, <code>chosen</code> et <code>rejected</code> sont présents dans les métadonnées de <strong>100 % des lignes</strong>. Cependant, la présence de la clé <code>golden_answer</code> ne signifie pas que sa valeur est renseignée : elle est vide dans <strong>25,14 % du train</strong>, <strong>24,96 % de la validation</strong> et <strong>11,07 % du test</strong>. Il faut donc distinguer clairement la présence structurelle du champ de la disponibilité réelle d’une réponse de référence.
  </p>

  <p>
    L’absence de <code>golden_answer</code> ne remet pas directement en cause l’utilisation d’une paire pour le DPO, puisque l’apprentissage repose principalement sur le triplet <code>prompt / chosen / rejected</code>. En revanche, lorsqu’une réponse de référence est disponible, elle peut constituer un signal supplémentaire utile pour contrôler la qualité clinique des préférences sélectionnées.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage DPO :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>conserver uniquement les lignes disposant d’un <code>prompt</code>, d’un <code>chosen</code> et d’un <code>rejected</code> valides et distincts ;</li>
    <li>supprimer les doublons stricts portant sur le triplet complet <code>prompt / chosen / rejected</code> en conservant un seul exemplaire ;</li>
    <li>ne pas dédupliquer sur le seul prompt, puisqu’un même prompt peut légitimement être associé à plusieurs comparaisons ;</li>
    <li>examiner et résoudre les paires présentant une <strong>préférence inversée</strong> avant leur intégration au dataset final ;</li>
    <li>surveiller les fortes différences de longueur entre <code>chosen</code> et <code>rejected</code> afin d’éviter un biais de préférence fondé principalement sur la longueur ;</li>
    <li>ne pas exclure automatiquement les lignes dont <code>golden_answer</code> est absent, ce champ n’étant pas indispensable au DPO ;</li>
    <li>utiliser le <code>golden_answer</code> lorsqu’il est disponible comme signal complémentaire de contrôle de la cohérence et de la qualité clinique ;</li>
    <li>conserver dans les exports de nettoyage les identifiants et métadonnées nécessaires pour tracer les déduplications, conflits et décisions de sélection.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">11. Audit des fuites entre splits</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Mesurer les chevauchements train, validation et test sur le contenu complet et les groupes indivisibles.
</div>


<p>
Les splits fournis par les sources sont analysés afin de détecter les chevauchements de contenu et de groupes logiques entre entraînement, validation et test. Ces contrôles permettent d'identifier les risques de fuite avant la reconstruction des splits définitifs.
</p>

In [21]:
# Regroupement des corpus

# Rattache train, validation et test à leur corpus source commun.
# Ce regroupement permet de rechercher les fuites uniquement entre splits comparables.
CORPUS_GROUP = {
    **{f"fmmcqa_{s}": "fmmcqa" for s in ["train", "validation", "test"]},
    **{f"mqal_mcqm_{s}": "mqal_mcqm" for s in ["train", "validation", "test"]},
    **{f"mqal_mcqu_{s}": "mqal_mcqu" for s in ["train", "validation", "test"]},
    **{f"umed_{s}": "umed" for s in ["train", "validation", "test"]},
    "mqal_oeq_test": "mqal_oeq",
    "mquad": "mquad"
}

audit_records["corpus_group"] = audit_records["dataset"].map(CORPUS_GROUP)


# Chevauchement entre splits

# Compare deux splits à partir d'une clé normalisée et conserve résumé et détails.
# Le taux mesure la part du split droit appartenant à des groupes déjà présents à gauche.
def split_overlap(
    df: pd.DataFrame,
    key: str,
    left_split: str,
    right_split: str,
    overlap_type: str
) -> tuple[pd.DataFrame, pd.DataFrame]:
    summaries, details = [], []

    for corpus_group, corpus in df.groupby("corpus_group", sort=False):
        left = corpus[corpus["split"].eq(left_split)]
        right = corpus[corpus["split"].eq(right_split)]

        if left.empty or right.empty:
            continue

        left_map = left.groupby(key)["id"].apply(list).to_dict()
        right_map = right.groupby(key)["id"].apply(list).to_dict()
        overlaps = set(left_map) & set(right_map)
        right_rows = sum(len(right_map[value]) for value in overlaps)
        comparison = f"{left_split}_{right_split}"

        summaries.append({
            "corpus_group": corpus_group,
            "comparison": comparison,
            "overlap_type": overlap_type,
            "overlapping_groups": len(overlaps),
            "right_rows_in_overlap": right_rows,
            "right_overlap_rate_pct": round(right_rows / len(right) * 100, 2)
        })

        details.extend({
            "corpus_group": corpus_group,
            "comparison": comparison,
            "overlap_type": overlap_type,
            "group_key": value,
            "left_ids": left_map[value],
            "right_ids": right_map[value]
        } for value in overlaps)

    return pd.DataFrame(summaries), pd.DataFrame(details)


# Audit des fuites

# Teste les trois couples de splits sur les entrées normalisées et groupes cliniques.
# Une présence commune signale une fuite potentielle à contrôler avant entraînement.
leakage_summaries, leakage_details = [], []

for left, right in [
    ("train", "validation"),
    ("train", "test"),
    ("validation", "test")
]:
    for key, overlap_type in [
        ("input_hash", "NORMALIZED_INPUT"),
        ("group_hash", "GROUP")
    ]:
        summary, details = split_overlap(
            audit_records,
            key,
            left,
            right,
            overlap_type
        )
        leakage_summaries.append(summary)
        leakage_details.append(details)

leakage_summary = pd.concat(leakage_summaries, ignore_index=True)
leakage_details_df = pd.concat(leakage_details, ignore_index=True)

<h4 style="color:#48C9B0;">Synthèse</h4>

<div style="border-left:4px solid #48C9B0; padding-left:15px; margin-left:5px; margin-bottom:10px;">

  <p style="margin-top:0;">
    L’audit de fuite entre splits met en évidence des niveaux de chevauchement très différents selon les corpus. <strong>FrenchMedMCQA</strong> présente une séparation globalement propre, avec des recouvrements très faibles entre train, validation et test. En revanche, <strong>MediQAl</strong> et surtout <strong>UltraMedical-Preference</strong> présentent des recouvrements plus importants qui devront être corrigés avant la constitution des datasets finaux.
  </p>

  <p>
    <strong>Chevauchements exacts ou normalisés :</strong> FrenchMedMCQA reste presque étanche, avec seulement <strong>0,32 %</strong> de la validation et <strong>0,16 %</strong> du test en recouvrement avec le train. MediQAl présente davantage de répétitions entre splits : jusqu’à <strong>3,00 %</strong> pour MCQM train-validation et <strong>4,22 %</strong> pour MCQU train-validation lorsque la comparaison porte sur les entrées normalisées.
  </p>

  <p>
    <strong>Chevauchements par groupe :</strong> les taux deviennent nettement plus élevés pour MediQAl. En MCQM, <strong>31,11 %</strong> de la validation et <strong>28,87 %</strong> du test appartiennent à des groupes déjà présents dans le train. En MCQU, ces taux atteignent respectivement <strong>36,39 %</strong> et <strong>39,65 %</strong>. Cela indique qu’un grand nombre d’exemples ne sont pas forcément identiques mot pour mot, mais appartiennent à une même question, un même cas clinique ou un même groupe logique réparti entre plusieurs splits.
  </p>

  <p>
    <strong>UltraMedical-Preference</strong> présente le signal le plus important entre train et validation : <strong>55,47 % des lignes de validation</strong> appartiennent à des prompts également présents dans le train. Le chevauchement train-test est beaucoup plus faible, à <strong>3,86 %</strong>. Une validation comportant plus de la moitié de prompts déjà vus pendant l’entraînement ne permettrait pas d’estimer correctement la capacité de généralisation du modèle DPO.
  </p>

  <p>
    <strong>Chevauchement inter-corpus :</strong> l’audit identifie également des entrées identiques entre <strong>MedQuad-KV</strong> et <strong>UltraMedical-Preference</strong>, y compris dans certains exemples du test UltraMedical. Cela suggère qu’une partie des prompts d’UltraMedical provient ou recoupe des questions présentes dans MedQuad-KV. Ce phénomène est particulièrement important puisque MedQuad-KV peut être utilisé pour le SFT alors qu’UltraMedical-Preference sert au DPO : un même contenu pourrait donc être rencontré à plusieurs étapes de l’entraînement ou se retrouver dans une évaluation ultérieure.
  </p>

  <p>
    Ces résultats montrent que les <strong>splits fournis par les sources ne doivent pas être repris aveuglément</strong> pour l’entraînement final. La séparation devra être reconstruite ou corrigée après déduplication, en utilisant les groupes de contenu plutôt que les seules lignes individuelles, afin qu’un même cas, prompt ou question ne puisse pas être réparti entre plusieurs ensembles.
  </p>

  <p style="margin-bottom:6px;">
    <strong>Décisions pour le nettoyage et la création des splits :</strong>
  </p>

  <ul style="line-height:1.6; margin-top:0; margin-bottom:0;">
    <li>supprimer tout chevauchement direct entre les futurs ensembles <strong>train, validation et test</strong> avant l’entraînement ;</li>
    <li>réaliser la séparation au niveau du <strong>groupe logique</strong> lorsque plusieurs variantes appartiennent au même cas clinique, prompt ou question ;</li>
    <li>corriger en priorité les splits MediQAl MCQM et MCQU, dont les taux de chevauchement par groupe sont trop élevés pour une évaluation fiable ;</li>
    <li>reconstruire ou assainir la validation DPO d’UltraMedical-Preference afin qu’elle ne contienne pas de prompts déjà utilisés dans le train ;</li>
    <li>conserver autant que possible le test comme ensemble strictement indépendant et exclure de l’entraînement toute entrée ou groupe qui y apparaît ;</li>
    <li>contrôler les chevauchements <strong>entre sources</strong>, notamment entre MedQuad-KV et UltraMedical-Preference, afin d’éviter une contamination entre le SFT, le DPO et les données d’évaluation ;</li>
    <li>effectuer la déduplication et la résolution des groupes <strong>avant</strong> la création définitive des splits ;</li>
    <li>enregistrer les groupes déplacés, exclus ou conservés afin de garantir la reproductibilité et la traçabilité de la séparation finale des données.</li>
  </ul>

</div>

<h2 style="color:#48C9B0;">12. Synthèse globale et export des rapports</h2>


<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:12px 16px; margin:16px 0;">
<strong>Objectif :</strong><br/>Rassembler les résultats, vérifier que les données brutes sont intactes et exporter des rapports cohérents sans répéter une sauvegarde dans chaque section.
</div>



<table style="border-collapse:collapse; width:100%; margin:12px 0;">
<thead style="background-color:#48C9B0; color:#ffffff;"><tr><th style="border:1px solid #ddd; padding:8px; text-align:left;">Décision</th><th style="border:1px solid #ddd; padding:8px; text-align:left;">Application future</th></tr></thead>
<tbody><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Schémas distincts</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Construire séparément SFT et DPO.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Contexte MediQAl</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Conserver s’il est nécessaire ; ne jamais l’imputer.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Réponses QCM</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Normaliser A–E et préserver le mode unique ou multiple.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Textes atypiques</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Signaler et revoir ; ne pas supprimer selon la longueur seule.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Doublons</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Comparer l’exemple complet, jamais la réponse seule.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Contradictions</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Quarantaine ou revue, sans correction médicale automatique.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">RGPD</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Masquage ciblé, revue contextuelle et second contrôle.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">DPO</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Dédupliquer les triplets, conserver les prompts distinctement comparés.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Fuites</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Regrouper cas cliniques et prompts avant toute création de split.</td></tr><tr><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Triage</td><td style="border:1px solid #ddd; padding:8px; vertical-align:top;">Indicateur de sélection uniquement, jamais label artificiel.</td></tr></tbody>
</table>

In [22]:
# Empreinte des fichiers

# Calcule le SHA-256 par blocs pour garantir l'intégrité et la traçabilité des fichiers.
# La lecture par blocs évite de charger entièrement les gros datasets en mémoire.
def file_sha256(path: Path) -> str:
    """Calcule l'empreinte SHA-256 d'un fichier."""
    hasher = hashlib.sha256()

    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            hasher.update(chunk)

    return hasher.hexdigest()

In [23]:
# Intégrité avant export

# Vérifie que la canonicalisation conserve les volumes et des identifiants valides.
# Une incohérence bloque immédiatement l'export des rapports d'audit.
if {name: len(df) for name, df in datasets.items()} != raw_row_counts:
    raise ValueError("Les volumes bruts ont changé.")

if not audit_records["id"].is_unique:
    raise ValueError("Des identifiants canoniques sont dupliqués.")

if audit_records["dataset"].isna().any():
    raise ValueError("Des enregistrements n'ont pas de dataset.")


# Sérialisation JSON

# Convertit les types NumPy et pandas en valeurs compatibles avec JSON.
# Les valeurs manquantes sont converties en null.
def json_ready(value):
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, (pd.Timestamp, datetime)):
        return value.isoformat()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if not isinstance(value, (list, dict, tuple)) and pd.isna(value):
        return None

    return value


# Export des rapports

# Sérialise chaque DataFrame d'audit et retourne ses informations de traçabilité.
# Le manifeste conserve le chemin relatif et le nombre de lignes exportées.
def save_dataframe(df: pd.DataFrame, name: str) -> dict:
    path = AUDIT_DIR / f"{name}.json"
    records = [
        {key: json_ready(value) for key, value in row.items()}
        for row in df.to_dict("records")
    ]

    path.write_text(
        json.dumps(records, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8"
    )

    return {
        "name": name,
        "path": str(path.relative_to(PROJECT_ROOT)),
        "rows": len(df)
    }


export_manifest = [
    save_dataframe(df, name)
    for name, df in REPORTS.items()
    if isinstance(df, pd.DataFrame)
]


# Empreintes des sources

# Calcule le SHA-256 de chaque fichier brut réellement audité.
# Le nettoyage pourra vérifier qu'il travaille exactement sur les mêmes sources.
raw_file_hashes = {
    name: file_sha256(RAW_DIR / spec["path"])
    for name, spec in DATASET_SPECS.items()
}


# Manifeste d'audit

# Centralise provenance, configuration, volumes, empreintes et rapports produits.
# Il constitue la trace reproductible de cette exécution de l'audit.
manifest = {
    "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    "seed": SEED,
    "tokenizer_model": TOKENIZER_MODEL,
    "raw_row_counts": raw_row_counts,
    "raw_file_hashes": raw_file_hashes,
    "canonical_rows": len(audit_records),
    "reports": export_manifest,
    "open_decisions": [
        "Confirm MedQuAD licensing before training use."
    ]
}

<div style="border-left:5px solid #48C9B0; background-color:#f2fbf9; color:#000000; padding:14px 18px; margin:18px 0;">
<strong>Conclusion :</strong><br/>
Les quatre corpus restent dans le périmètre de l’audit. FrenchMedMCQA et MediQAl MCQU/MCQM constituent le vivier SFT principal. MediQAl OEQ reste protégé pour l’évaluation. UltraMedical-Preference reste la source DPO. MedQuAD demeure bloqué pour l’entraînement tant que la variante locale n’est pas documentée. Le nettoyage ne pourra commencer qu’après examen des contradictions, des candidats RGPD et des fuites identifiées.
</div>